In [1]:
import pandas as pd

In [2]:
results_V01 = pd.read_csv(
    "results/v0.1_baseline_ragas_results.csv"
)

display(
    results_V01[["case_id", "faithfulness", "context_precision", "response_relevancy", "factual_correctness"]]
)

,case_id,faithfulness,context_precision,response_relevancy,factual_correctness
0,text_simple_01,0.481481,0.000,0.734717,0.80
1,text_complex_01,0.342105,0.325,0.663383,0.55
2,numeric_simple_01,0.233333,0.000,0.753206,0.15
3,numeric_complex_01,0.190476,0.000,0.774549,0.00
4,numeric_complex_02,0.200000,0.000,0.743218,0.15
5,comparison_01,0.000000,0.250,0.851608,0.15
6,robustness_noisy_01,0.631579,0.000,NaN,0.48
7,out_of_scope_01,0.000000,0.000,0.000000,0.53

Le principal problème se trouve au niveau du retriever, pas uniquement du LLM :

- Context Precision est nulle pour six questions sur huit.
- Les réponses sont souvent pertinentes dans leur formulation.
- Mais elles ne disposent pas des bonnes données, ce qui réduit Faithfulness et Factual Correctness.

C’est particulièrement visible pour les questions numériques :

- numeric_complex_01 obtient 0 en exactitude factuelle ;
- numeric_complex_02 obtient 0,15 ;
- comparison_01 obtient une pertinence élevée (0,85), mais une fidélité nulle et une exactitude de seulement 0,15.

Le LLM comprend donc la demande, mais FAISS ne lui fournit probablement pas toutes les lignes nécessaires pour filtrer, classer ou comparer.

In [3]:
for _, row in results_V01.iterrows():
    print("Question :")
    print(row["question"])

    print("\nRéponse :")
    print(row["answer"])

    print("\n" + "-" * 80 + "\n")

Question :
Quels sont les trois joueurs les plus souvent mentionnés dans les commentaires ?

Réponse :
Ah, excellente question ! D’après les échanges récents sur Reddit (et en croisant les tendances de *shit talk*, de débats stratégiques et de rivalités), voici les **trois joueurs les plus souvent cités** dans les commentaires animés, avec une nuance sur leur impact réel vs. leur image médiatique :

---

### **1. Tyrese Haliburton (Thunder OKC)**
**Pourquoi ?**
- **Le "shit talk" roi** : Haliburton est souvent accusé (à tort ou à raison) d’être le plus vocal des joueurs NBA, avec des répliques cinglantes contre ses adversaires (ex. : *"I’m not here to play for you"* vs. les Warriors en 2023). Les fans adorent (ou détestent) son côté provocateur, surtout en playoffs.
- **Rivalité historique** : Son duel avec Jayson Tatum (Celtics) ou Devin Booker (Warriors) a alimenté les débats sur la "mentalité de leader" vs. la "mentalité de joueur". Les commentaires sur Reddit (et les réseaux sociaux) sont souvent polarisés entre *"le meilleur joueur de la ligue"* et *"le plus arrogant"*.
- **Statistiques qui le défendent** : Avec un **USG% de 35%+** et un **PIE élevé** (impact global), il est souvent cité comme un joueur clé pour les Thunder, même si son style de jeu (dribble + tir) peut diviser.

**Débat à creuser** :
- *"Est-ce que son shit talk est une stratégie ou une faiblesse ?"* (Certains fans le voient comme un atout pour motiver son équipe, d’autres comme un risque de blessure émotionnelle).
- *"Pourrait-il être plus efficace si il réduisait son USG% pour éviter les collisions ?"* (Ex. : son **PACE élevé** en 2024 était critique pour les Thunder).

---

### **2. Jayson Tatum (Celtics)**
**Pourquoi ?**
- **Le "dragon" des playoffs** : Tatum est souvent cité comme l’un des joueurs les plus intimidants en finale (ex. : *"Tatum vs. Haliburton"* est devenu un match à ne pas manquer). Les fans des Celtics adorent son jeu de poste et son leadership, tandis que les fans des autres équipes le voient comme un *"génie qui écrase les défenses"*.
- **Rivalité avec les Warriors** : Son duel avec Stephen Curry et Klay Thompson a été l’un des plus médiatisés de la saison. Les commentaires sur Reddit sont souvent hilarants (ex. : *"Tatum a volé le ballon de Curry en 2023"*).
- **Statistiques qui le soutiennent** : Avec un **FG% de 50%** et un **PIE de 20+**, il est un pilier offensif, même si son **USG% (25-30%)** peut être critiqué pour son manque de polyvalence.

**Débat à creuser** :
- *"Est-ce que Tatum est un joueur de poste ou un joueur complet ?"* (Certains fans le voient comme un *"Big Man"* qui manque de vitesse, d’autres comme un *"playmaker"* grâce à ses passes).
- *"Pourrait-il être plus efficace si il jouait plus de minutes en défense ?"* (Son **rebonds offensifs** sont élevés, mais son **PIE** pourrait baisser si son équipe le sollicite moins).

---

### **3. Devin Booker (Warriors)**
**Pourquoi ?**
- **Le "moteur" des Warriors** : Booker est souvent cité comme le joueur le plus explosif en playoffs, avec des performances fulgurantes (ex. : *"Booker a marqué 50+ en 2023"* vs. les Celtics). Les fans des Warriors adorent son jeu de tir et son énergie, tandis que les fans des autres équipes le voient comme un *"spectacle"* qui peut être dangereux.
- **Rivalité avec Haliburton** : Leur duel en playoffs 2023 a été l’un des plus attendus, avec des commentaires du type *"Qui va gagner ce match ?"* (et souvent *"Booker"*).
- **Statistiques qui le défendent** : Avec un **3P% de 40%** et un **USG% de 30%**, il est un joueur clé pour les Warriors, même si son **PACE** peut être critiqué pour son manque de contrôle du rythme.

**Débat à creuser** :
- *"Est-ce que Booker est un joueur de tir ou un joueur de jeu ?"* (Certains fans le voient comme un *"scorer"* qui manque de défense, d’autres comme un *"playmaker"* grâce à ses passes).
- *"Pourrait-il être plus efficace si il jouait moins de minutes en attaque ?"* (Son **PIE** pourrait baisser si son équipe le sollicite moins).

---

### **Bonus : Pourquoi ces joueurs ?**
- **Ils incarnent des débats** : Haliburton (mentalité), Tatum (poste), Booker (tir) → ces trois joueurs représentent des styles de jeu différents qui divisent les fans.
- **Ils sont médiatisés** : Leurs performances en playoffs (et leurs échanges verbaux) sont souvent relayés par les médias, ce qui amplifie leur présence dans les commentaires.
- **Ils ont des stats qui parlent** : Leur **USG%**, **PIE**, et **rebonds offensifs** sont souvent cités dans les analyses, ce qui les rend plus visibles.

---
### **Question pour les fans :**
*"Si vous deviez choisir un joueur qui a le plus influencé les débats sur Reddit cette saison, ce serait-il Haliburton, Tatum, ou Booker ? Et pourquoi ?"*
(Je peux vous donner des exemples précis de commentaires récents si vous voulez !)

---
*PS : D’après les données de votre fichier (USG%, PIE, etc.), Haliburton et Booker ont des USG% élevés, ce qui explique pourquoi ils sont souvent cités dans les débats sur le "contrôle du jeu". Tatum, lui, a un USG% plus modéré, mais son impact défensif et son FG% en font un joueur très discuté.*

--------------------------------------------------------------------------------

Question :
Quels sont les principaux sujets de débat dans les commentaires des supporters ?

Réponse :
Voici une analyse structurée des **principaux sujets de débat récurrents** dans les commentaires des supporters sur la NBA (basée sur les échanges Reddit et les tendances observées), avec une approche analytique et nuancée pour alimenter le débat :

---

### **1. Le "Two Best Teams" vs. "Rigging" et Parité**
**Sujet central** : *"Pourquoi les deux équipes les plus performantes (statistiquement) se rencontrent-elles en Finale ?"*
- **Débat sur la parité** :
  - **Pour** : La NBA mise sur la parité (ex. : cap flexible, salaires élevés pour les stars) pour éviter les dynasties (ex. : Warriors 2015-2019). Les fans de petites équipes (ex. : Pacers, Thunder) critiquent cette "rigueur" comme favorisant les marchés médiatique (ex. : Lakers, Celtics).
  - **Contre** : Certains (comme *Klaw95*) accusent un "manipulation" pour éviter les séries "trop longues" (ex. : Warriors vs. Spurs en 2016) ou des matchs "trop faciles" (ex. : Warriors vs. Heat en 2014). *Dreamlion_Inc* (Wizards) souligne que les fans de petites équipes sont "exclués" de l’attention médiatique.
  - **Nuance analytique** :
    - Les stats (PIE, USG%) montrent que les deux équipes sont effectivement les meilleures, mais le "two best" est un mythe : les Warriors 2015-2016 avaient des records de 73-9, mais les Celtics 2022-23 (67-17) ont dominé en playoffs. La NBA utilise des critères comme le *Final Four* (moins de 4 équipes) pour équilibrer.
    - *Janal88sepsis* et *Snakescipio* soulignent que le cap (même "second apron") limite les salaires des petites équipes, réduisant leur capacité à rivaliser.

---

### **2. Le "Shit Talk" vs. Culture du Joueur**
**Sujet central** : *"Tyrese Haliburton est-il un shit talker ou juste un joueur vocal ?"*
- **Débat sur l’éthique** :
  - **Pour** : Les fans (ex. *Sure_Station9370*) soulignent que Haliburton est un leader charismatique, et son "shit talk" (ex. : *"I’m gonna eat you up"*) est souvent perçu comme une stratégie de pression psychologique, pas de méchanceté. *Rapper_Laugh* note que les joueurs comme Giannis ou Steph Curry ont aussi utilisé ce langage.
  - **Contre** : Certains (ex. *tachudda*) critiquent le "laundry" (le côté "lavage" du sport) et préfèrent se concentrer sur les performances. *GodWhyPlease* généralise : *"Root for players > teams"*, comme dans le football américain où les fans s’identifient aux joueurs (ex. : Steelers malgré leur médiocrité).
  - **Analyse** :
    - Le shit talk est un outil de motivation collective (ex. : les Warriors vs. Spurs en 2016). Les stats (USG%, PIE) montrent que Haliburton est un joueur offensif clé, mais son impact en playoffs dépendra de son adaptation à la pression des Finals.

---

### **3. Le Fan Engagement et la Médiatisation**
**Sujet central** : *"Pourquoi les médias (MSM) et les fans se concentrent-ils sur les joueurs plutôt que les équipes ?"*
- **Débat sur l’identification** :
  - **Pour** : *Overall_Turnip8405* et *FMCam2o* estiment que la NBA est plus "fun" avec des équipes changeantes (ex. : Warriors vs. Celtics en 2023). Les fans s’attachent aux stars (ex. : Steph, Giannis) plutôt qu’aux dynasties (ex. : Lakers 2020s).
  - **Contre** : *bebging_brother* et *Janal88sepsis* critiquent le manque de soutien aux petites équipes (ex. : Steelers) ou la dépendance aux salaires (ex. : cap). *LordBaneoftheSith* dénonce un "capitalisme" qui réduit les fans à des "pocket watchers".
  - **Analyse** :
    - Les stats (PACE, POSS) montrent que les équipes avec des joueurs stars (ex. : Thunder 2023) ont un rythme de jeu plus élevé, mais cela ne garantit pas la victoire. La NBA mise sur l’ADN des franchises (ex. : Pacers avec un jeu collectif) pour éviter la dépendance aux stars.

---

### **4. Le Référage et l’Outrage**
**Sujet central** : *"Pourquoi les fans accusent-ils les refs de favoriser leur équipe ?"*
- **Débat sur la perception** :
  - **Exemples extrêmes** : *StillOutrageous1961* cite des cas de refs "anti-homme" (ex. : Lakers vs. Warriors en 2016). Cependant, les stats (ex. : *NBA.com* sur les calls) montrent que les refs sont formés pour équilibrer.
  - **Réponse nuancée** : *Klaw95* et *Troll_Enthusiast* soulignent que les fans de petites équipes sont plus sensibles aux "injustices", mais les données (ex. : *NBA’s officiating data*) montrent une neutralité relative. Le problème vient souvent de la **subjectivité** (ex. : les calls controversés en playoffs).

---

### **5. Le Futur de la NBA : Parité et Dynamique des Franchises**
**Sujet central** : *"La NBA va-t-elle rester paritaire ou revenir à des dynasties ?"*
- **Débat sur l’avenir** :
  - **Pour la parité** : *Snakescipio* et *Janal88sepsis* estiment que le cap (même "second apron") et les règles anti-dynastie (ex. : 3 ans sans Finales) maintiennent l’équilibre. Les stats (ex. : *PIE*) montrent que les équipes comme les Pacers ou Thunder ont un potentiel offensif.
  - **Contre** : *GodWhyPlease* et *tachudda* craignent que la parité ne réduise l’engagement (ex. : les Steelers comme exemple négatif). *Overall_Turnip8405* défend l’idée que la parité rend le sport plus excitant (ex. : Warriors vs. Celtics en 2023).
  - **Analyse** :
    - La NBA a déjà testé des modèles (ex. : *NBA 2K* avec des dynasties), mais les données montrent que les équipes avec des joueurs stars (ex. : Lakers 2020s) dominent les playoffs. Le défi est de trouver un équilibre entre parité et spectacle.

---

### **Synthèse des Dynamiques de Débat**
| **Thème**               | **Fans "Pro" (Critiques positives)**               | **Fans "Con" (Critiques négatives)**               | **Analyse NBA**                                  |
|-------------------------|----------------------------------------------------|----------------------------------------------------|--------------------------------------------------|
| **Two Best Teams**      | Parité = plus de spectacle.                        | "Rigging" pour éviter les séries longues.         | Stats + stratégie (Final Four).                 |
| **Shit Talk**           | Stratégie de pression psychologique.              | Méchanceté ou "laundry".                            | Culture du jeu collectif.                        |
| **Médiatisation**       | Fans = supporters de joueurs (ex. : Steph).        | Manque de soutien aux petites équipes.             | Mix de stars et d’ADN des franchises.           |
| **Référage**            | Référage neutre (données).                        | Accusations de partialité.                         | Subjectivité + formation.                       |
| **Parité**              | Évite les dynasties.                              | Réduit l’engagement (ex. : Steelers).              | Équilibre entre spectacle et compétitivité.     |

---
### **Pourquoi ces débats persistent ?**
1. **Contraste entre données et émotion** : Les stats (PIE, USG%) montrent une logique de parité, mais les fans s’identifient aux équipes ou joueurs (ex. : Warriors vs. Lakers).
2. **Inégalités économiques** : Les petites équipes (ex. : Pacers) sont sous-représentées dans les médias, ce qui nourrit le ressentiment (*Janal88sepsis*).
3. **Culture du sport** : Le NBA est moins "team-oriented" que le football américain (ex. : Steelers), ce qui crée des frustrations (*GodWhyPlease*).
4. **Événementiel vs. Performance** : Les fans veulent à la fois des stars (ex. : Haliburton) et des équipes compétitives (ex. : Thunder).

---
### **Question pour approfondir**
*"Si la NBA devait supprimer le cap pour favoriser les petites équipes, quels impacts sur les playoffs et les ratings auraient-t-il ?"* (À explorer avec les stats de *NBA.com* sur les salaires et les performances.)

--------------------------------------------------------------------------------

Question :
Quels joueurs possèdent le meilleur pourcentage de réussite à trois points ?

Réponse :
**NBA Analyst AI** ici, et je vais creuser cette question avec passion ! Voici une analyse **détaillée et nuancée** des meilleurs tireurs à 3 points de la NBA actuelle (saison 2023-24), en croisant les données disponibles avec une approche **statistique et contextuelle** pour éviter les simplifications.

---

### **Top 5 des meilleurs pourcentages de réussite à 3 points (3P%)**
*(Basé sur les données disponibles dans votre fichier, avec des ajustements pour les joueurs actifs en 2023-24)*

| **Joueur**                     | **Équipe**       | **3P%** (moyenne) | **3PA/match** | **Points clés supplémentaires**                                                                 |
|--------------------------------|------------------|-------------------|---------------|------------------------------------------------------------------------------------------------|
| **Jayson Tatum**               | Boston Celtics   | **42.5%**         | 12.8          | *Le plus complet : 3P% + TS% (68.5%) + rebonds défensifs (10.5 DREB%).* **Impact offensif + défensif.** |
| **Jaren Jackson Jr.**          | Milwaukee Bucks  | **42.2%**         | 11.5          | *Le "Big Three" de Milwaukee : 3P% + OREB% (15.5%) + +/– (10.5).* **Équilibre entre tir et jeu physique.** |
| **Tyrese Haliburton**          | Sacramento Kings | **41.8%**         | 11.2          | *Le MVP 2023 : 3P% + AST% (35.5%) + NETRTG (18.5).* **Clé de l’attaque des Kings.** |
| **Devin Booker**               | Phoenix Suns     | **41.5%**         | 10.8          | *Le "Shooting Machine" : 3P% + TS% (67.0%) + USG% (45%).* **Rythme de jeu explosif.** |
| **Jalen Brunson**              | New York Knicks  | **41.2%**         | 9.7           | *Le "Playmaker" : 3P% + AST% (33.0%) + +/– (12.0).* **Contre les défenses en 2x2.** |

---
### **Analyse approfondie**
#### **1. Pourquoi ces chiffres ?**
- **Votre fichier** ne contient pas les données **2023-24 complètes** (certains joueurs comme Haliburton ou Brunson ont des stats en cours). Cependant, les moyennes **2022-23** (dernière saison complète) montrent une tendance claire :
  - **Tatum (42.5%)** et **Jackson Jr. (42.2%)** sont **au-dessus de 40%** depuis 2021, avec des **rebonds défensifs exceptionnels** (Jackson Jr. est le meilleur DREB% de la ligue).
  - **Booker (41.5%)** et **Haliburton (41.8%)** dominent les **True Shooting % (TS%)**, ce qui signifie qu’ils tirent **plus efficacement** (y compris les lancers francs).

#### **2. Le piège des stats : 3P% vs. Impact global**
- **Un 3P% de 42% ne suffit pas** :
  - **Tyrese Haliburton** a un **3P% légèrement inférieur (41.8%)**, mais son **AST% (35.5%)** et son **NETRTG (18.5)** en font un joueur **plus impactant** que Booker (qui a un 3P% plus élevé mais un **USG% de 45%** = plus de possessions, donc plus de risques).
  - **Jaren Jackson Jr.** est souvent sous-estimé : son **3P% + OREB%** en fait un **1-2 de Milwaukee**, mais son **USG% (30%)** limite son rôle offensif pur.

#### **3. Qui est le "meilleur" ?**
- **Si on se base uniquement sur le 3P%** → **Jayson Tatum (42.5%)** et **Jaren Jackson Jr. (42.2%)** sont les rois.
- **Si on ajoute l’impact global** → **Tyrese Haliburton** (MVP 2023) ou **Devin Booker** (leader des Suns) sont **plus complets**.

---
### **Débat : 3P% vs. Autres indicateurs**
**Fan 1** : *"Pourquoi ne regarde-t-on pas le nombre de tirs à 3 points (3PA) ? Un joueur avec 10.5 3PA/match est plus dangereux qu’un autre avec 9.7."*
→ **Réponse** : Exact ! **Jayson Tatum (12.8 3PA)** et **Jaren Jackson Jr. (11.5 3PA)** sont **plus dangereux** que Brunson (9.7 3PA). Mais :
- **Haliburton (11.2 3PA)** a un **3P% légèrement inférieur**, mais son **AST% et son +/–** en font un **1-2 offensif**.
- **Booker (10.8 3PA)** tire **plus efficacement** (TS% de 67%), mais son **USG% élevé** signifie qu’il utilise **plus de possessions**.

**Fan 2** : *"Pourquoi ne considère-t-on pas le True Shooting % (TS%) ? Un joueur avec un TS% de 68% est plus efficace qu’un autre avec un 3P% de 42%."*
→ **Réponse** : **Vrai !** Un **TS% de 68%** (comme Haliburton ou Booker) signifie qu’ils tirent **plus efficacement** (y compris les lancers francs). **Tatum (68.5%)** et **Booker (67.0%)** sont **plus efficaces** que Jackson Jr. (65.0%) malgré un 3P% plus élevé.

---
### **Top 3 des joueurs les plus dangereux à 3 points (critères combinés)**
| **Rang** | **Joueur**               | **Critères clés**                                                                 |
|----------|--------------------------|-----------------------------------------------------------------------------------|
| 1        | **Tyrese Haliburton**    | 3P% (41.8%) + TS% (68.5%) + AST% (35.5%) + NETRTG (18.5) → **Clé offensive des Kings**. |
| 2        | **Devin Booker**         | 3P% (41.5%) + TS% (67.0%) + USG% (45%) → **Rythme de jeu explosif**.             |
| 3        | **Jayson Tatum**         | 3P% (42.5%) + DREB% (10.5%) + +/– (10.0) → **1-2 offensif + défensif**.          |

---
### **Conclusion : Qui est le meilleur tireur à 3 points ?**
- **Si vous voulez le plus de tirs réussis** → **Jayson Tatum (42.5%)**.
- **Si vous voulez le plus d’impact global** → **Tyrese Haliburton (MVP 2023)**.
- **Si vous voulez le plus de possessions efficaces** → **Devin Booker (USG% de 45%)**.

**Et vous, quel joueur vous semble le plus dangereux ?** 🏀
*(Je peux affiner en croisant avec les données de +/– ou de NETRTG si vous avez des ajustements !)*

--------------------------------------------------------------------------------

Question :
Parmi les joueurs ayant tenté au moins 100 tirs à trois points, lequel possède le meilleur pourcentage de réussite ?

Réponse :
**Réponse structurée avec débat analytique (basée sur les données disponibles et les tendances NBA) :**

---
### **Le champion du 3PT en % de réussite : *Reggie Miller* (1995–2005) – **43,4% sur 100+ tirs à 3 points**
*(Dernière mise à jour : saison 2004–05, avec des données historiques vérifiables)*

#### **Pourquoi lui ?**
1. **Statistiques historiques** :
   - **43,4% sur 100+ tirs à 3 points** (selon les archives NBA pré-2010, où les données étaient moins fragmentées).
   - **Top 5 des meilleurs % de 3PT de l’histoire** (avant l’ère moderne des tirants comme Steph Curry ou Klay Thompson).
   - **Exemple concret** : En 1995–96, il a marqué **40% sur 100+ tirs à 3 points** (saison où il a aussi marqué **28,8 PPG**).

2. **Comparaison avec les "modernes" (post-2010)** :
   - **Curry** : 41,4% sur 100+ tirs (saison 2015–16, mais avec un volume bien supérieur et un % moyen de 42,8% sur 200+ tirs).
   - **Thompson** : 40,5% sur 100+ tirs (saison 2019–20).
   - **Miller** reste **le plus précis** parmi les joueurs ayant marqué **au moins 100 tirs à 3 points** *sans compter les saisons récentes*.

3. **Contexte historique** :

# V0.1 - Analyse des résultats de l’évaluation RAGAS 

## 1. Résultats globaux

| Métrique            | Moyenne approximative | Interprétation                                                                          |
| ------------------- | --------------------: | --------------------------------------------------------------------------------------- |
| Faithfulness        |                  0,26 | Faible : plusieurs affirmations ne sont pas soutenues par les contextes récupérés       |
| Context Precision   |                  0,07 | Très faible : les passages récupérés sont rarement adaptés à la question                |
| Response Relevancy  |                  0,65 | Correcte : les réponses restent généralement liées au sujet de la question              |
| Factual Correctness |                  0,35 | Faible : les réponses contiennent de nombreuses informations différentes des références |

Les réponses sont donc généralement liées au sujet demandé, mais elles utilisent rarement les bonnes informations et contiennent de nombreuses erreurs factuelles.

L’analyse manuelle montre également que certains scores RAGAS sont trop généreux. Les métriques automatiques doivent donc être complétées par une vérification humaine des réponses.

---

## 2. Analyse par question

### 2.1 Joueurs les plus souvent mentionnés

**Question :**

> Quels sont les trois joueurs les plus souvent mentionnés dans les commentaires ?

**Réponse attendue :**

> Reggie Miller, Stephen Curry et Dwyane Wade.

**Réponse générée :**

> Tyrese Haliburton, Jayson Tatum et Devin Booker.

La réponse est incorrecte : aucun des trois joueurs attendus n’est identifié.

Elle contient également plusieurs hallucinations :

* Tyrese Haliburton est associé au Thunder alors qu’il joue aux Pacers ;
* Devin Booker est associé aux Warriors alors qu’il joue aux Suns ;
* plusieurs rivalités, citations et statistiques sont inventées.

Le score `Factual Correctness` de `0,80` est donc incohérent avec le contenu réel de la réponse. Le modèle juge a probablement été influencé par la longueur de la réponse et par la présence de nombreux termes liés à la NBA.

**Verdict manuel : échec.**

---

### 2.2 Principaux sujets de débat

**Question :**

> Quels sont les principaux sujets de débat dans les commentaires des supporters ?

La réponse retrouve certains thèmes réellement présents :

* la médiatisation de la NBA ;
* les équipes issues de petits marchés ;
* la parité entre les équipes ;
* l’intérêt du public pour une finale entre le Thunder et les Pacers.

Cependant, plusieurs thèmes importants sont absents :

* les équipes et joueurs les plus impressionnants des playoffs ;
* l’efficacité et la place historique de Reggie Miller ;
* l’avantage du terrain ;
* le classement des équipes ;
* le système de play-in.

La réponse ajoute également des thèmes secondaires ou non suffisamment soutenus par les documents :

* la manipulation des résultats ;
* le trash-talk de Tyrese Haliburton ;
* l’arbitrage ;
* différentes citations et statistiques non présentes dans les sources.

**Verdict manuel : réponse partiellement correcte, mais incomplète et fortement enrichie par des informations inventées.**

---

### 2.3 Meilleur pourcentage à trois points

**Question :**

> Quels joueurs possèdent le meilleur pourcentage de réussite à trois points ?

**Réponse attendue :**

> Alondes Williams et Skal Labissiere avec 100 %, chacun sur une seule tentative.

La réponse générée désigne notamment Jayson Tatum, Jaren Jackson Jr., Tyrese Haliburton, Devin Booker et Jalen Brunson.

Elle ne retrouve donc aucun des deux joueurs attendus et invente plusieurs pourcentages, équipes et statistiques.

Le score `Factual Correctness` de `0,15` est cohérent avec cette réponse très éloignée de la référence.

**Verdict manuel : échec complet.**

---

### 2.4 Meilleur pourcentage avec au moins 100 tentatives

**Question :**

> Parmi les joueurs ayant tenté au moins 100 tirs à trois points, lequel possède le meilleur pourcentage de réussite ?

**Réponse attendue :**

> Seth Curry avec 45,6 % sur 184 tentatives.

**Réponse générée :**

> Reggie Miller avec 43,4 %.

La réponse utilise des données historiques externes au lieu d’appliquer le filtre demandé aux données du fichier Excel.

Le score `Factual Correctness` de `0` correspond correctement à cet échec.

**Verdict manuel : échec complet.**

---

### 2.5 Cinq meilleurs marqueurs

**Question :**

> Quels sont les cinq joueurs ayant marqué le plus de points, classés du premier au cinquième ?

**Classement attendu :**

1. Shai Gilgeous-Alexander : 2 485 points ;
2. Anthony Edwards : 2 180 points ;
3. Nikola Jokić : 2 072 points ;
4. Giannis Antetokounmpo : 2 037 points ;
5. Jayson Tatum : 1 930 points.

La réponse générée propose principalement :

1. Jayson Tatum ;
2. Nikola Jokić ;
3. Giannis Antetokounmpo ;
4. Luka Dončić ;
5. Jrue Holiday.

Elle mentionne ensuite Shai Gilgeous-Alexander dans son développement, mais ne produit jamais le classement attendu. Elle confond également les points totaux et les moyennes de points par match.

La présence de quelques joueurs appartenant réellement au classement explique probablement le score `Factual Correctness` de `0,15`, mais la réponse finale reste incorrecte.

**Verdict manuel : échec.**

---

### 2.6 Comparaison des rebonds

**Question :**

> Compare le nombre total de rebonds de Shai Gilgeous-Alexander et d’Anthony Edwards.

**Réponse attendue :**

> Shai Gilgeous-Alexander totalise 380 rebonds, contre 450 pour Anthony Edwards. Anthony Edwards a donc capté 70 rebonds de plus.

La réponse générée estime environ 1 800 rebonds pour Shai Gilgeous-Alexander et 1 200 pour Anthony Edwards. Elle conclut donc, à tort, que Shai est le meilleur rebondeur.

Elle contient aussi plusieurs hallucinations :

* Shai Gilgeous-Alexander est présenté comme un pivot ;
* Anthony Edwards est également assimilé à un intérieur ;
* les totaux et pourcentages de rebonds sont inventés ;
* les moyennes par match sont très éloignées des données réelles.

Le score élevé de `Response Relevancy` (`0,85`) signifie seulement que la réponse parle bien des deux joueurs et des rebonds. Il ne mesure pas l’exactitude des nombres ou de la conclusion.

**Verdict manuel : échec complet.**

---

### 2.7 Robustesse face aux fautes

**Question :**

> c ki les joueur ki on le meilleur pourcentaj a 3 points ?

Le système comprend correctement l’intention malgré les fautes. La robustesse linguistique est donc satisfaisante.

Cependant, la réponse reprend un classement incorrect proche de celui fourni pour la question numérique simple. Elle ne cite pas Alondes Williams et Skal Labissiere.

La valeur manquante de `Response Relevancy` correspond à un échec technique du calcul de la métrique. Elle ne doit pas être interprétée comme un score nul.

**Verdict manuel :**

* compréhension de la question : réussie ;
* exactitude de la réponse : échouée.

---

### 2.8 Question hors périmètre

**Question :**

> Quel temps fera-t-il demain à Toulouse ?

Le système indique correctement que les données fournies ne contiennent pas d’informations météorologiques. Le mécanisme de refus fonctionne donc.

Cependant, la réponse continue ensuite sur plusieurs paragraphes avec des analogies entre la météo et la NBA ainsi que de nouvelles affirmations non vérifiées.

Elle aurait dû s’arrêter après une phrase, par exemple :

> Je ne dispose pas de données météorologiques permettant de répondre à cette question.

Cela explique les résultats suivants :

* `Response Relevancy = 0` : la majorité de la réponse est inutile par rapport à la question ;
* `Faithfulness = 0` : les développements supplémentaires ne sont pas soutenus par les données ;
* `Factual Correctness = 0,53` : l’idée principale correspond partiellement à la réponse de référence.

**Verdict manuel : refus fonctionnellement correct, mais réponse trop longue et contenant des hallucinations.**

---

## 3. Bilan manuel

Sur les huit réponses évaluées :

* aucune réponse métier n’est entièrement correcte ;
* une réponse est partiellement correcte : les principaux sujets de débat ;
* une réponse refuse correctement une demande hors périmètre, mais de manière trop longue ;
* six réponses sont incorrectes ;
* le système comprend correctement la question comportant des fautes, mais fournit une réponse factuellement incorrecte.

Les résultats montrent donc que la pertinence thématique est meilleure que l’exactitude factuelle. Le système comprend généralement le sujet de la demande, mais ne parvient pas à récupérer ou exploiter correctement les données nécessaires.

---

## 4. Limites identifiées

### 4.1 Récupération insuffisante

La valeur moyenne très faible de `Context Precision` indique que les chunks transmis au LLM sont rarement les plus utiles pour répondre aux questions.

Le modèle doit alors produire une réponse avec des informations incomplètes ou non pertinentes.

### 4.2 Limites de FAISS pour les calculs globaux

Les questions demandant de :

* calculer un maximum ;
* appliquer un filtre ;
* classer plusieurs joueurs ;
* comparer des valeurs ;
* compter les mentions dans l’ensemble des documents ;

nécessitent une analyse globale des données.

Une recherche sémantique limitée aux cinq chunks les plus proches ne garantit pas que toutes les lignes nécessaires seront récupérées. FAISS recherche des passages sémantiquement proches, mais ne réalise pas directement de filtre, de tri ou d’agrégation sur l’ensemble du tableau.

### 4.3 Prompt de génération trop permissif

Le modèle adopte systématiquement un style de « débat analytique » et produit des réponses longues, même lorsque la question demande un résultat numérique simple.

Ce comportement favorise :

* l’ajout d’informations inutiles ;
* l’utilisation de connaissances générales externes ;
* l’invention de statistiques ;
* les erreurs d’équipes, de saisons et de positions ;
* l’éloignement par rapport au contexte récupéré.

Le prompt devrait imposer au modèle :

1. d’utiliser uniquement les informations présentes dans le contexte ;
2. de ne jamais compléter une information manquante avec ses connaissances générales ;
3. de signaler clairement lorsque les données sont insuffisantes ;
4. de répondre directement et brièvement ;
5. de ne pas transformer systématiquement la réponse en débat.

### 4.4 Limites du modèle juge

Certains scores de `Factual Correctness` ne correspondent pas à la qualité réelle des réponses.

L’exemple le plus évident est la première question :

* réponse entièrement incorrecte ;
* `Factual Correctness = 0,80`.

Le modèle juge `ministral-3b-2512` semble donc avoir des difficultés à comparer précisément une réponse longue avec une référence courte. Les scores automatiques doivent rester accompagnés d’une vérification manuelle.

---

## 5. Pistes d’amélioration

Les principales améliorations possibles sont :

1. utiliser un traitement structuré pour les questions numériques ;
2. appliquer directement les filtres, tris et agrégations sur le DataFrame ;
3. réserver FAISS aux questions textuelles et à la recherche dans les commentaires Reddit ;
4. router les questions vers le bon type de traitement avant la génération ;
5. renforcer le prompt afin d’interdire les connaissances externes et les valeurs inventées ;
6. produire des réponses plus courtes et directement centrées sur la question ;
7. utiliser un modèle juge plus performant pour les métriques RAGAS ;
8. conserver une vérification humaine sur un échantillon de réponses.

Une architecture hybride serait plus adaptée :

* questions textuelles sur Reddit : recherche vectorielle avec FAISS ;
* questions numériques sur les joueurs : requêtes structurées sur le DataFrame ;
* génération finale : formulation concise à partir des résultats calculés.

---

## 6. Conclusion

> L’analyse manuelle révèle que les réponses restent généralement liées au sujet, mais qu’elles contiennent de nombreuses erreurs factuelles et hallucinations. Les scores automatiques, notamment l’exactitude factuelle, doivent donc être interprétés avec prudence. Les principales limites proviennent de l’utilisation d’une recherche vectorielle pour des calculs globaux et d’un prompt de génération trop permissif. Une architecture hybride combinant recherche sémantique et traitement structuré des statistiques permettrait d’améliorer fortement la fiabilité des réponses.

In [4]:


display(
    results_V01[["case_id", "faithfulness", "context_precision", "response_relevancy", "factual_correctness"]]
)

results_V02 = pd.read_csv(
    "results/v0.2_pydantic_ai_results.csv"
)

display(
    results_V02[["case_id", "faithfulness", "context_precision", "response_relevancy", "factual_correctness"]]
)

,case_id,faithfulness,context_precision,response_relevancy,factual_correctness
0,text_simple_01,0.481481,0.000,0.734717,0.80
1,text_complex_01,0.342105,0.325,0.663383,0.55
2,numeric_simple_01,0.233333,0.000,0.753206,0.15
3,numeric_complex_01,0.190476,0.000,0.774549,0.00
4,numeric_complex_02,0.200000,0.000,0.743218,0.15
5,comparison_01,0.000000,0.250,0.851608,0.15
6,robustness_noisy_01,0.631579,0.000,NaN,0.48
7,out_of_scope_01,0.000000,0.000,0.000000,0.53

,case_id,faithfulness,context_precision,response_relevancy,factual_correctness
0,text_simple_01,0.720000,1.00,0.746829,0.19
1,text_complex_01,NaN,NaN,0.820751,0.84
2,numeric_simple_01,0.657143,0.00,0.777291,0.06
3,numeric_complex_01,0.086957,0.25,0.834734,0.47
4,numeric_complex_02,0.093750,0.00,0.742770,0.29
5,comparison_01,0.000000,0.25,0.855278,0.68
6,robustness_noisy_01,0.500000,0.00,0.708446,0.23
7,out_of_scope_01,0.105263,0.00,0.000000,0.57

# V0.2 - Analyse Ragas 

La version **v0.2** obtient des résultats globalement supérieurs à la baseline, avec une amélioration des quatre métriques moyennes : **faithfulness (0,309)**, **context precision (0,214)**, **response relevancy (0,686)** et **factual correctness (0,416)**.

L’intégration de **Pydantic et Pydantic AI** sécurise les flux et conserve le bon fonctionnement du pipeline RAG. Ces résultats restent toutefois à interpréter avec prudence en raison de certaines valeurs manquantes et de la variabilité liée à l’évaluation par LLM.

In [5]:
display(
    results_V01[["case_id", "faithfulness", "context_precision", "response_relevancy", "factual_correctness"]]
)

results_V03 = pd.read_csv(
    "results/v0.3_sql_results.csv"
)

display(
    results_V03[["case_id", "faithfulness", "context_precision", "response_relevancy", "factual_correctness"]]
)

,case_id,faithfulness,context_precision,response_relevancy,factual_correctness
0,text_simple_01,0.481481,0.000,0.734717,0.80
1,text_complex_01,0.342105,0.325,0.663383,0.55
2,numeric_simple_01,0.233333,0.000,0.753206,0.15
3,numeric_complex_01,0.190476,0.000,0.774549,0.00
4,numeric_complex_02,0.200000,0.000,0.743218,0.15
5,comparison_01,0.000000,0.250,0.851608,0.15
6,robustness_noisy_01,0.631579,0.000,NaN,0.48
7,out_of_scope_01,0.000000,0.000,0.000000,0.53

,case_id,faithfulness,context_precision,response_relevancy,factual_correctness
0,text_simple_01,NaN,0.000000,0.000000,0.00
1,text_complex_01,1.000000,0.250000,0.801893,0.21
2,numeric_simple_01,1.000000,0.587302,0.805857,0.22
3,numeric_complex_01,0.666667,0.166667,0.840104,0.00
4,numeric_complex_02,1.000000,0.166667,0.815115,1.00
5,comparison_01,NaN,0.166667,0.861286,1.00
6,robustness_noisy_01,0.857143,0.166667,0.714024,0.00
7,out_of_scope_01,0.600000,0.000000,0.000000,0.33

In [6]:
for _, row in results_V03.iterrows():
    print("Question :")
    print(row["question"])

    print("\nRéponse attendue :")
    print(row["reference"])

    print("\nRéponse Obtenue:")
    print(row["answer"])

    print("\n" + "-" * 80 + "\n")

Question :
Quels sont les trois joueurs les plus souvent mentionnés dans les commentaires ?

Réponse attendue :
Les trois joueurs les plus souvent mentionnés dans les commentaires sont Reggie Miller, Stephen Curry et Dwyane Wade, dans cet ordre.

Réponse Obtenue:
Les commentaires documentés ne permettent pas d'identifier clairement les trois joueurs les plus souvent mentionnés dans les échanges sur Reddit. Les références disponibles concernent principalement des discussions générales ou des thèmes liés à la NBA, sans attribution directe et répétée à des joueurs spécifiques.

--------------------------------------------------------------------------------

Question :
Quels sont les principaux sujets de débat dans les commentaires des supporters ?

Réponse attendue :
Les principaux débats portent sur les équipes et joueurs les plus impressionnants des playoffs, l'intérêt médiatique et les audiences d'une finale entre équipes de petits marchés, l'efficacité et la place historique de Reggie Miller, ainsi que l'avantage du terrain, le classement des équipes et le système de play-in.

Réponse Obtenue:
Les principaux sujets de débat dans les commentaires des supporters concernent principalement :

1. **L'équité entre les équipes et la parité dans la NBA**, notamment en raison des contraintes budgétaires (hard cap) et leur impact sur les performances des petits marchés.
2. **La rivalité et la toxicité entre les supporters de deux équipes statistiques parmi les meilleures en playoffs**, ainsi que les attentes autour de leur confrontation en Finale NBA.
3. **L'importance des joueurs individuels par rapport aux équipes**, avec une tendance à privilégier les stars (comme Steph Curry ou Giannis) plutôt que les équipes locales, surtout après le retrait de ces joueurs.
4. **Les perceptions de rigueur ou d'injustice dans les arbitrages ou les résultats**, notamment en lien avec des équipes spécifiques ou des joueurs controversés.
5. **L'engagement des fans et leur attachement aux équipes ou aux joueurs**, avec des critiques sur la promotion des équipes versus celle des athlètes, ainsi que des réactions émotionnelles liées à leur support local.

Ces débats reflètent des opinions variées sur l'équité, l'attachement émotionnel et la valeur perçue de la NBA.

--------------------------------------------------------------------------------

Question :
Quels joueurs possèdent le meilleur pourcentage de réussite à trois points ?

Réponse attendue :
Alondes Williams et Skal Labissiere possèdent le meilleur pourcentage de réussite à trois points avec 100 %, chacun ayant réussi son unique tentative.

Réponse Obtenue:
Voici les cinq joueurs avec le meilleur pourcentage de réussite à trois points pour la saison 2024-25 :

| Rang | Joueur               | Valeur 3P% |
|------|----------------------|------------|
| 1    | Alondes Williams      | 100,0%     |
| 2    | Skal Labissière      | 100,0%     |
| 3    | PJ Dozier             | 66,7%      |
| 4    | Patrick Baldwin Jr.  | 56,5%      |
| 5    | Dru Smith             | 53,3%      |

Les joueurs **Alondes Williams** et **Skal Labissière** détiennent le meilleur pourcentage à 100 %.

--------------------------------------------------------------------------------

Question :
Parmi les joueurs ayant tenté au moins 100 tirs à trois points, lequel possède le meilleur pourcentage de réussite ?

Réponse attendue :
Seth Curry possède le meilleur pourcentage de réussite parmi les joueurs ayant tenté au moins 100 tirs à trois points, avec 45,6 % sur 184 tentatives.

Réponse Obtenue:
Seth Curry détient le meilleur pourcentage de réussite aux tirs à trois points parmi les joueurs ayant tenté au moins 100 tirs à trois points en saison 2024-25, avec un **45,6 %**.

*(Aucune URL n'est disponible pour ce joueur.)*

--------------------------------------------------------------------------------

Question :
Quels sont les cinq joueurs ayant marqué le plus de points, classés du premier au cinquième ?

Réponse attendue :
Les cinq joueurs ayant marqué le plus de points sont Shai Gilgeous-Alexander avec 2 485 points, Anthony Edwards avec 2 180 points, Nikola Jokić avec 2 072 points, Giannis Antetokounmpo avec 2 037 points et Jayson Tatum avec 1 930 points, dans cet ordre.

Réponse Obtenue:
Voici les cinq joueurs ayant marqué le plus de points lors de la saison 2024-25 :

| Rang | Joueur                     | Nombre de points totaux |
|------|----------------------------|--------------------------|
| 1    | Shai Gilgeous-Alexander     | 2 485                    |
| 2    | Anthony Edwards            | 2 180                    |
| 3    | Nikola Jokić                | 2 072                    |
| 4    | Giannis Antetokounmpo      | 2 037                    |
| 5    | Jayson Tatum               | 1 930                    |

--------------------------------------------------------------------------------

Question :
Compare le nombre total de rebonds de Shai Gilgeous-Alexander et d’Anthony Edwards.

Réponse attendue :
Shai Gilgeous-Alexander totalise 380 rebonds, contre 450 pour Anthony Edwards. Anthony Edwards a donc capté 70 rebonds de plus.

Réponse Obtenue:
En saison 2024-25, **Shai Gilgeous-Alexander** a marqué **380 rebonds totaux**, tandis qu'**Anthony Edwards** en a totalisé **450 rebonds** pour la même saison.

--------------------------------------------------------------------------------

Question :
c ki les joueur ki on le meilleur pourcentaj a 3 points ?

Réponse attendue :
Alondes Williams et Skal Labissiere possèdent le meilleur pourcentage de réussite à trois points avec 100 %, chacun sur une seule tentative.

Réponse Obtenue:
Voici les cinq joueurs avec le pourcentage de réussite aux tirs à 3 points le plus élevé pour la saison 2024-25 :

| Rang | Joueur                     | 3P%   |
|------|-----------------------------|-------|
| 1    | Alondes Williams             | 100%  |
| 2    | Skal Labissiere             | 100%  |
| 3    | PJ Dozier                   | 66,7% |
| 4    | Patrick Baldwin Jr.        | 56,5% |
| 5    | Dru Smith                   | 53,3% |

Pour plus de détails sur leur performance ou leur équipe, je peux fournir des liens vers leurs fiches NBA si nécessaire.

--------------------------------------------------------------------------------

Question :
Quel temps fera-t-il demain à Toulouse ?

Réponse attendue :
Je ne dispose pas de données météorologiques permettant de répondre à cette question.

Réponse Obtenue:
Je ne peux pas répondre à cette question, car elle ne concerne pas les statistiques NBA de la saison 2024-25 ni les données disponibles dans les contextes fournis.

--------------------------------------------------------------------------------

## Analyse de la V03 : agent avec tool SQL

Cette analyse combine les scores RAGAS, une évaluation humaine
des réponses et l'examen des contextes et des traces Logfire.

Les métriques non calculées sont conservées comme valeurs
manquantes et exclues des moyennes.

In [19]:
display()

metrics = [
    "faithfulness",
    "context_precision",
    "response_relevancy",
    "factual_correctness",
]

print("Nombre de cas V01 :", len(results_V01))
print("Nombre de cas V03 :", len(results_V03))

print(
    "Mêmes identifiants :",
    set(results_V01["case_id"]) == set(results_V03["case_id"]),
)

display(results_V03.info())

display(
    results_V03[
        ["case_id", "category", "question"] + metrics
    ]
)

summary_V03 = pd.DataFrame({
    "Moyenne": results_V03[metrics].mean(),
    "Scores calculés": results_V03[metrics].count(),
    "Scores manquants": results_V03[metrics].isna().sum(),
})

display(summary_V03.round(3))

Nombre de cas V01 : 8
Nombre de cas V03 : 8
Mêmes identifiants : True
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   case_id              8 non-null      object
 1   category             8 non-null      object
 2   question             8 non-null      object
 3   reference            8 non-null      object
 4   answer               8 non-null      object
 5   retrieved_contexts   8 non-null      object
 6   faithfulness         6 non-null      float64
 7   context_precision    8 non-null      float64
 8   response_relevancy   8 non-null      float64
 9   factual_correctness  8 non-null      float64
dtypes: float64(4), object(6)
memory usage: 772.0+ bytes

None

,case_id,category,question,faithfulness,context_precision,response_relevancy,factual_correctness
0,text_simple_01,text_simple,Quels sont les trois joueurs les plus souvent ...,NaN,0.000000,0.000000,0.00
1,text_complex_01,text_complex,Quels sont les principaux sujets de débat dans...,1.000000,0.250000,0.801893,0.21
2,numeric_simple_01,numeric_simple,Quels joueurs possèdent le meilleur pourcentag...,1.000000,0.587302,0.805857,0.22
3,numeric_complex_01,numeric_complex,Parmi les joueurs ayant tenté au moins 100 tir...,0.666667,0.166667,0.840104,0.00
4,numeric_complex_02,numeric_complex,Quels sont les cinq joueurs ayant marqué le pl...,1.000000,0.166667,0.815115,1.00
5,comparison_01,comparison,Compare le nombre total de rebonds de Shai Gil...,NaN,0.166667,0.861286,1.00
6,robustness_noisy_01,robustness_noisy,c ki les joueur ki on le meilleur pourcentaj a...,0.857143,0.166667,0.714024,0.00
7,out_of_scope_01,out_of_scope,Quel temps fera-t-il demain à Toulouse ?,0.600000,0.000000,0.000000,0.33

                     Moyenne  Scores calculés  Scores manquants
faithfulness           0.854                6                 2
context_precision      0.188                8                 0
response_relevancy     0.605                8                 0
factual_correctness    0.345                8                 0

### Analyse question 1

In [8]:
import ast

row = results_V03.loc[
    results_V03["case_id"] == "text_simple_01"
].iloc[0]

print("QUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

# Le CSV stocke la liste des contextes sous forme de texte.
contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Quels sont les trois joueurs les plus souvent mentionnés dans les commentaires ?

RÉPONSE ATTENDUE :
Les trois joueurs les plus souvent mentionnés dans les commentaires sont Reggie Miller, Stephen Curry et Dwyane Wade, dans cet ordre.

RÉPONSE OBTENUE :
Les commentaires documentés ne permettent pas d'identifier clairement les trois joueurs les plus souvent mentionnés dans les échanges sur Reddit. Les références disponibles concernent principalement des discussions générales ou des thèmes liés à la NBA, sans attribution directe et répétée à des joueurs spécifiques.

------------------------------ CONTEXTE 1 ------------------------------

41                     USG%                Usage Rate – % des actions utilisées par le joueur
42                     PACE                        Rythme de jeu (possessions par 48 minutes)
43                      PIE           Player Impact Estimate – évaluation globale de l’impact
44                     POSS                                Nombre total de possessions jouées

------------------------------ CONTEXTE 2 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
86                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
87                                             Players    Nombre de point total                          FGM       Pourcentage de tirs réussis  Pourcentage de réussite aux tirs à 3 points  Pourcentage de réussite aux lancers francs  Rebonds offensifs  Estimation de l’impact du joueur
88                             Shai Gilgeous-Alexander                     2485                          859                              51.9                                         37.5                                        89.8                 68                              19.9

------------------------------ CONTEXTE 3 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
86                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
87                                             Players    Nombre de point total                          FGM       Pourcentage de tirs réussis  Pourcentage de réussite aux tirs à 3 points  Pourcentage de réussite aux lancers francs  Rebonds offensifs  Estimation de l’impact du joueur
88                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN

------------------------------ CONTEXTE 4 ------------------------------

Dictionnaire des données                                                        Unnamed: 1
0                    Player                                                     Nom du joueur
1                      Team                               Équipe du joueur (code à 3 lettres)
2                       Age                                                     Âge du joueur
3                        GP                             Nombre de matchs joués (Games Played)
4                         W             Nombre de victoires de l'équipe lors des matchs joués
5                         L                                                Nombre de défaites
6                       Min                                 Minutes moyennes jouées par match
7                       PTS                               Points marqués en moyenne par match
8                       FGM                         Tirs réussis par match (Field Goals Made)
9                       FGA                     Tirs tentés par match (Field Goals Attempted)
10                      FG%                                  Pourcentage de réussite aux tirs
11                 15:00:00                                 Minutes jouées après 15:00 de jeu
12                      3PA                                  Tirs à 3 points tentés par match
13                      3P%                                Pourcentage de réussite à 3 points

------------------------------ CONTEXTE 5 ------------------------------

above all else; but most casual viewers don't.
4 1
Répondre
IScraggyBo
-14 j
medias obsession is just the same as the commenters on reddit's obsession; don't blame the MSM for
something prevalent in the 'fans' as well
U 1
Répondre
BethesdaFR
Sponsorisé(e)
Salut Reddit... Nous recherchons des aventuriers
Quelle serait votre meilleure
attaque contre ce
dragon
Dites-le-nous dans les commentaires ci-dessous.
En savoir plus
elderscrollsonline com
The Alder Scrolls
Jayveesac
-15 j
Comm. du top 1%
Pacers vs. Thunder is gonna be a great and toxic series at the same time
356
Répondre
twrs_29
~15 j
Comm. du top 1%
doubt it will even be extremely toxic between the Pacers and Thunder fans, mostly just everyone else
210
Répondre
Sure_Station9370
~15 j
Tyrese Haliburton has to be one of the biggest shit talkers in the league.
wanna see how that
goes down on the court when the stakes are highest.
61
Répondre
twrs_29
~15 j
Comm. du top 1%
wavefree3
~15 j
Comm. du top 1%
Rapper_Laugh
~15 j
https:/lwww. reddit.comlrInbalcomments/ 1kxixihlhow
it_that
the_two
best_teams
the
playoffsl
11/23
will
12/06/2025 13.09
How is it that the two best teams in the
playoffs based on stats
having
chance of playing against each other in the Finals, is
Accéder au contenu principal
Se connecter
much shit?
know he's always talking; but that doesn't necessarily mean shit talking. It often
reads to me more like he's just a very vocal player. I've seen clips of him cheering his

### Cas text_simple_01 — Joueurs les plus mentionnés

![Trace Logfire de la question 1](logfire/Logfire_question_1.png)

**Résultat :** le classement attendu n'est pas fourni.

**Contextes récupérés :** quatre passages issus de l'Excel sont
hors sujet. Le cinquième contient des commentaires Reddit, mais
ne fournit aucun comptage permettant de classer les joueurs
par fréquence de mention.

**Réponse :** l'abstention évite un classement non justifié.
Cependant, la formulation généralise les limites des extraits
récupérés à l'ensemble des commentaires et minimise la présence
de mentions de joueurs.

**Diagnostic :** la recherche documentaire ne fournit pas les
preuves nécessaires. De plus, un classement global par fréquence
nécessite un comptage sur le corpus ; les cinq passages les plus
similaires ne garantissent pas ce classement.

**Observation Logfire et Tool SQL :** la trace contient une recherche FAISS
et un seul appel au modèle, sans appel au tool SQL.
Le pipeline dure environ 29 secondes, dont 28,6 secondes
pour l'appel au modèle.
L'absence d'appel SQL est cohérente avec cette question
La base de statistiques NBA ne permet pas de compter les mentions
dans les commentaires. 

**Métriques :** les scores nuls de pertinence et d'exactitude
reflètent l'absence de la réponse attendue. Le score de fidélité
est manquant à cause d'une erreur de calcul du juge.

**Pistes à tester ultérieurement :**
- Filtrer la recherche vers les documents Reddit pour les questions
  sur les commentaires.
- Nettoyer les publicités et les éléments d'interface des documents.
- Prévoir un comptage des mentions pour les questions de fréquence.
- Limiter les formulations d'abstention aux extraits disponibles.

### Analyse question 2

In [9]:
row = results_V03.loc[
    results_V03["case_id"] == "text_complex_01"
].iloc[0]

print("QUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Quels sont les principaux sujets de débat dans les commentaires des supporters ?

RÉPONSE ATTENDUE :
Les principaux débats portent sur les équipes et joueurs les plus impressionnants des playoffs, l'intérêt médiatique et les audiences d'une finale entre équipes de petits marchés, l'efficacité et la place historique de Reggie Miller, ainsi que l'avantage du terrain, le classement des équipes et le système de play-in.

RÉPONSE OBTENUE :
Les principaux sujets de débat dans les commentaires des supporters concernent principalement :

1. **L'équité entre les équipes et la parité dans la NBA**, notamment en raison des contraintes budgétaires (hard cap) et leur impact sur les performances des petits marchés.
2. **La rivalité et la toxicité entre les supporters de deux équipes statistiques parmi les meilleures en playoffs**, ainsi que les attentes autour de leur confrontation en Finale NBA.
3. **L'importance des joueurs individuels par rapport aux équipes**, avec une tendance à privilégier les stars (comme Steph Curry ou Giannis) plutôt que les équipes locales, surtout après le retrait de ces joueurs.
4. **Les perceptions de rigueur ou d'injustice dans les arbitrages ou les résultats**, notamment en lien avec des équipes spécifiques ou des joueurs controversés.
5. **L'engagement des fans et leur attachement aux équipes ou aux joueurs**, avec des critiques sur la promotion des équipes versus celle des athlètes, ainsi que des réactions émotionnelles liées à leur support local.

Ces débats reflètent des opinions variées sur l'équité, l'attachement émotionnel et la valeur perçue de la NBA.

------------------------------ CONTEXTE 1 ------------------------------

above all else; but most casual viewers don't.
4 1
Répondre
IScraggyBo
-14 j
medias obsession is just the same as the commenters on reddit's obsession; don't blame the MSM for
something prevalent in the 'fans' as well
U 1
Répondre
BethesdaFR
Sponsorisé(e)
Salut Reddit... Nous recherchons des aventuriers
Quelle serait votre meilleure
attaque contre ce
dragon
Dites-le-nous dans les commentaires ci-dessous.
En savoir plus
elderscrollsonline com
The Alder Scrolls
Jayveesac
-15 j
Comm. du top 1%
Pacers vs. Thunder is gonna be a great and toxic series at the same time
356
Répondre
twrs_29
~15 j
Comm. du top 1%
doubt it will even be extremely toxic between the Pacers and Thunder fans, mostly just everyone else
210
Répondre
Sure_Station9370
~15 j
Tyrese Haliburton has to be one of the biggest shit talkers in the league.
wanna see how that
goes down on the court when the stakes are highest.
61
Répondre
twrs_29
~15 j
Comm. du top 1%
wavefree3
~15 j
Comm. du top 1%
Rapper_Laugh
~15 j
https:/lwww. reddit.comlrInbalcomments/ 1kxixihlhow
it_that
the_two
best_teams
the
playoffsl
11/23
will
12/06/2025 13.09
How is it that the two best teams in the
playoffs based on stats
having
chance of playing against each other in the Finals, is
Accéder au contenu principal
Se connecter
much shit?
know he's always talking; but that doesn't necessarily mean shit talking. It often
reads to me more like he's just a very vocal player. I've seen clips of him cheering his

------------------------------ CONTEXTE 2 ------------------------------

important once Steph retires for example
29
Répondre
tachudda
~15 j
Yeah,
root for players more than the laundry they are wearing
Répondre
2 réponses supplémentaires
GodWhyPlease
~15 j
The Steelers are a horrible
example
haven't had a losing season in 20 years_
But yeah; NFL has mastered it
0 4
Répondre
begging_brother
"15 j
"Not losing" rarely drives fan engagement. 2 decades of mediocrity from a small market
team ought to shrink the fan base It does in nearly
other case in every other sport.
In the NFL it doesn't at all.
10
Répondre
reponses
supplémentaires
Janal88sepsis
-15 j
And the hard cap makes ot easier for small market teams, nba needs to figure it's shit out on
that if
want parity
4 4
Répondre
Snakescipio
-15 j
The second apron's as close to a hard
as we're gonna get; and we're definitely in this
age of parity right now. In previous years the Celtics probably just eats an injury year from
Tatum and then run it back; but now it looks like
're gonna blow up the roster.
4 7
Répondre
2 réponses supplémentaires
Dakozi
~15 j
https://www reddit.comirinbalcommentsl 1kxixihlhow
is_it_that_the_two
best_teams
the
playoffsl
8/23
they
they
every
they
cap
they'
12/06/2025 13.09
How is it that the two best teams in the
playoffs based on stats
having
chance of playing against each other in the Finals, is
Accéder au contenu principal
Se connecter
Ill never say it was full on rigged; but there was a massive benefit to
having KC go far in the
playoffs
4 1 &
Répondre
lbegging_brother

------------------------------ CONTEXTE 3 ------------------------------

41                     USG%                Usage Rate – % des actions utilisées par le joueur
42                     PACE                        Rythme de jeu (possessions par 48 minutes)
43                      PIE           Player Impact Estimate – évaluation globale de l’impact
44                     POSS                                Nombre total de possessions jouées

------------------------------ CONTEXTE 4 ------------------------------

Pittsburgh Steelers remain one of the most popular teams in the league; even though the city is
quite small and
haven't had stellar success in recent years. The internet is convinced that the
NFL is rigging games in favor of Kansas City, the 3Oth largest media market in the country. Dallas,
LA, New York; Miami; Chicago; any of these major markets could be in the Super Bowl and the
ratings would be largely on par with a Green
vs Buffalo Super Bowl.
105
Répondre
Overall_Turnip8405
~15 j
exactly!
the NBA moves in that direction; it makes the league so much more fun to
watch:
love that no team has repeated in a long time; it's so much more
interesting
36
Répondre
FMCam2o
~15 j
https://www reddit.comirinbalcommentsl 1kxixihlhow_is_t_that_the_two
best_teams
the
playoffsl
7/23
from
doing
doing
they
Bay
hope
12/06/2025 13.09
How is it that the two best teams in the
playoffs based on stats
having
chance of playing against each other in the Finals, is
Accéder au contenu principal
Se connecter
Outside of my hometown Hawks
don't care about teams but do about players. I'm a Hawks
fan but also a Bron, Steph; and Giannis fan and
suspect a lot of basketball fans are the same
way where
only care about their hometown team and then are fans of players second so
the NBA doesn't promote teams as much as the players. The Warriors will cease to be
important once Steph retires for example
29
Répondre
tachudda
~15 j
Yeah,
root for players more than the laundry they are wearing
Répondre

------------------------------ CONTEXTE 5 ------------------------------

~15 j
hate basketball.
couldn't my team score more
points than the other team. Refs were
clearly against us.
0
Répondre
(StillOutrageous1961
~15 j
https:/lwww reddit.comlrInbalcomments/ 1kxixih/how
it_that_the_two
best_teams
the
playoffsl
4/23
They
against
thing
top
Yup,
Why
12/06/2025 13.09
How is it that the two best teams in the
playoffs based on stats
having
chance of playing against each other in the Finals, is
Accéder au contenu principal
Se connecter
Klaw95
-15 j
Comm. du top 1%
Everyone acting like they are NBA executives caring about ratings and shit. In reality; they are just mad
it's not their team
72
Répondre
Dreamlion_Inc
~15 j
will openly say, as a Wizards fan; that
can't even be mad about something my team will no have
relevance in
16
Répondre
Troll_Enthusiast
-15 j
Soon
0
Répondre
zimbabwes
-15 j
A wizards fan? I'II
you in my prayers
don't know how you haven't lost your mind
already
4 1 &
Répondre
Dreamlion_Inc
-15 j
Only the strongest wills can endure in the DC arena
0
Répondre
réponse supplémentaire
LordBaneoftheSith
~15 j
Comm. du top 1%
Capitalism
so
thoroughly poisoned American brains
're pocket watching the entertainment
instead of actually watching it. You have artist stans posting about their stream numbers instead of
their art. It's depressing:.
51
Répondre
Jburglin
~15 j
Well for artists that stuff really does matter; if it affects how much
get paid. For NBA fans it

### Cas text_complex_01 — Principaux sujets de débat

![Trace Logfire de la question 2](logfire/Logfire_question_2.png)

**Résultat :** la réponse identifie plusieurs débats pertinents,
mais ne couvre qu’une partie des thèmes attendus.

**Contextes récupérés :** quatre passages proviennent du même fil
Reddit et un passage Excel est hors sujet. Les extraits couvrent
la parité, les petits marchés, la rivalité entre supporters et
l’attachement aux stars. Ils ne couvrent pas Reggie Miller,
l’avantage du terrain, le classement ou le play-in.

**Réponse :** elle reprend correctement plusieurs thèmes présents.
Cependant, les audiences restent peu explicitées et certains
passages concernant la NFL sont généralisés à la NBA.

**Diagnostic :** la recherche manque de diversité pour produire
une synthèse de l’ensemble des commentaires. Les omissions
proviennent principalement des contextes récupérés, avec quelques
imprécisions supplémentaires dans la synthèse.

**Observation Logfire et tool SQL :** la trace montre une recherche
FAISS de 383 ms, suivie d’un seul appel au modèle d’environ
1,55 seconde. Le pipeline dure environ 1,95 seconde.
Aucun appel au tool SQL n’est observé, ce qui est adapté :
la question porte sur les commentaires, pas sur les statistiques.

**Métriques :** la fidélité de 1,00 et la pertinence de 0,80
concordent avec une réponse largement fondée sur les extraits.
La précision des contextes de 0,25 et l’exactitude factuelle
de 0,21 signalent une couverture limitée. Ce dernier score
ne signifie pas que tous les thèmes présentés sont faux.

**Pistes à tester ultérieurement :**
- Filtrer la recherche vers les documents Reddit.
- Diversifier les extraits pour les questions de synthèse.
- Nettoyer les publicités et les éléments d’interface.
- Distinguer les commentaires NBA des comparaisons avec la NFL.

### Analyse Question 3

In [10]:
row = results_V03.loc[
    results_V03["case_id"] == "numeric_simple_01"
].iloc[0]

print("QUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Quels joueurs possèdent le meilleur pourcentage de réussite à trois points ?

RÉPONSE ATTENDUE :
Alondes Williams et Skal Labissiere possèdent le meilleur pourcentage de réussite à trois points avec 100 %, chacun ayant réussi son unique tentative.

RÉPONSE OBTENUE :
Voici les cinq joueurs avec le meilleur pourcentage de réussite à trois points pour la saison 2024-25 :

| Rang | Joueur               | Valeur 3P% |
|------|----------------------|------------|
| 1    | Alondes Williams      | 100,0%     |
| 2    | Skal Labissière      | 100,0%     |
| 3    | PJ Dozier             | 66,7%      |
| 4    | Patrick Baldwin Jr.  | 56,5%      |
| 5    | Dru Smith             | 53,3%      |

Les joueurs **Alondes Williams** et **Skal Labissière** détiennent le meilleur pourcentage à 100 %.

------------------------------ CONTEXTE 1 ------------------------------

Dictionnaire des données                                                        Unnamed: 1
0                    Player                                                     Nom du joueur
1                      Team                               Équipe du joueur (code à 3 lettres)
2                       Age                                                     Âge du joueur
3                        GP                             Nombre de matchs joués (Games Played)
4                         W             Nombre de victoires de l'équipe lors des matchs joués
5                         L                                                Nombre de défaites
6                       Min                                 Minutes moyennes jouées par match
7                       PTS                               Points marqués en moyenne par match
8                       FGM                         Tirs réussis par match (Field Goals Made)
9                       FGA                     Tirs tentés par match (Field Goals Attempted)
10                      FG%                                  Pourcentage de réussite aux tirs
11                 15:00:00                                 Minutes jouées après 15:00 de jeu
12                      3PA                                  Tirs à 3 points tentés par match
13                      3P%                                Pourcentage de réussite à 3 points

------------------------------ CONTEXTE 2 ------------------------------

27                      TD3            Triple-doubles (≥10 dans trois catégories principales)
28                    + / -  Plus-Minus (écart de score lorsque le joueur est sur le terrain)
29                   OFFRTG             Offensive Rating (points marqués par 100 possessions)
30                   DEFRTG           Defensive Rating (points encaissés par 100 possessions)
31                   NETRTG                                      Net Rating = OFFRTG - DEFRTG
32                     AST%     Pourcentage d'assists – implication dans les passes décisives
33                   AST/TO                                    Ratio passes / pertes de balle
34                AST RATIO                              Ratio d’assists pour 100 possessions
35                    OREB%           Pourcentage de rebonds offensifs parmi ceux disponibles
36                    DREB%                                                  Idem en défensif
37                     REB%              Pourcentage de rebonds totaux parmi ceux disponibles
38                 TO RATIO              Turnover Ratio – pertes de balle par 100 possessions
39                     EFG%                     Effective Field Goal % (pondère les 3 points)
40                      TS%               True Shooting % (inclut FG et FT dans l'efficacité)
41                     USG%                Usage Rate – % des actions utilisées par le joueur

------------------------------ CONTEXTE 3 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
86                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
87                                             Players    Nombre de point total                          FGM       Pourcentage de tirs réussis  Pourcentage de réussite aux tirs à 3 points  Pourcentage de réussite aux lancers francs  Rebonds offensifs  Estimation de l’impact du joueur
88                             Shai Gilgeous-Alexander                     2485                          859                              51.9                                         37.5                                        89.8                 68                              19.9

------------------------------ CONTEXTE 4 ------------------------------

41                     USG%                Usage Rate – % des actions utilisées par le joueur
42                     PACE                        Rythme de jeu (possessions par 48 minutes)
43                      PIE           Player Impact Estimate – évaluation globale de l’impact
44                     POSS                                Nombre total de possessions jouées

------------------------------ CONTEXTE 5 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
86                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
87                                             Players    Nombre de point total                          FGM       Pourcentage de tirs réussis  Pourcentage de réussite aux tirs à 3 points  Pourcentage de réussite aux lancers francs  Rebonds offensifs  Estimation de l’impact du joueur
88                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN

------------------------------ CONTEXTE 6 ------------------------------

Source : tool SQL NBA, saison 2024-25.
{"status": "ok", "sql": "SELECT\n    p.player_name AS Player,\n    s.three_point_pct AS \"3P%\",\n    p.team_name AS Team\nFROM\n    stats s\nJOIN\n    players p ON p.player_id = s.player_id\nJOIN\n    reports r ON r.report_id = s.report_id\nWHERE\n    r.season = '2024-25'\n    AND s.three_point_pct IS NOT NULL\nORDER BY\n    s.three_point_pct DESC, p.player_name ASC\nLIMIT 5", "columns": ["Player", "3P%", "Team"], "rows": [{"Player": "Alondes Williams", "3P%": 100.0, "Team": "Detroit Pistons"}, {"Player": "Skal Labissiere", "3P%": 100.0, "Team": "Sacramento Kings"}, {"Player": "PJ Dozier", "3P%": 66.7, "Team": "Minnesota Timberwolves"}, {"Player": "Patrick Baldwin Jr,", "3P%": 56.5, "Team": "Los Angeles Clippers"}, {"Player": "Dru Smith", "3P%": 53.3, "Team": "Miami Heat"}], "truncated": false, "count": 5}

------------------------------ CONTEXTE 7 ------------------------------

Source : tool SQL NBA, saison 2024-25.
{"status": "ok", "sql": "SELECT\n    p.player_name,\n    s.three_point_pct\nFROM\n    stats s\nJOIN\n    players p ON p.player_id = s.player_id\nJOIN\n    reports r ON r.report_id = s.report_id\nWHERE\n    r.season = '2024-25'\n    AND s.three_point_pct IS NOT NULL\nORDER BY\n    s.three_point_pct DESC, p.player_name ASC\nLIMIT 5", "columns": ["player_name", "three_point_pct"], "rows": [{"player_name": "Alondes Williams", "three_point_pct": 100.0}, {"player_name": "Skal Labissiere", "three_point_pct": 100.0}, {"player_name": "PJ Dozier", "three_point_pct": 66.7}, {"player_name": "Patrick Baldwin Jr,", "three_point_pct": 56.5}, {"player_name": "Dru Smith", "three_point_pct": 53.3}], "truncated": false, "count": 5}

### Cas numeric_simple_01 — Meilleur pourcentage à trois points

![Trace Logfire de la question 3](logfire/Logfire_question_3.png)

**Résultat :** les deux joueurs attendus sont correctement identifiés :
Alondes Williams et Skal Labissiere, avec 100 %. La réponse ne précise
pas que chacun n’a tenté qu’un seul tir.

**Contextes récupérés :** les cinq passages FAISS ne permettent pas
d’établir le classement. Les deux résultats SQL fournissent les mêmes
cinq joueurs et pourcentages, repris correctement dans la réponse.

**Réponse :** les noms et les valeurs correspondent aux résultats SQL.
Le tableau propose cinq joueurs, puis souligne les deux premiers
ex æquo. Le faible nombre de tentatives manque pour contextualiser
leur pourcentage de 100 %.

**Diagnostic :** le tool SQL permet de répondre correctement malgré
des contextes documentaires insuffisants. Les requêtes utilisent
la bonne colonne, three_point_pct, avec un tri décroissant.
Cependant, elles ne récupèrent pas three_points_attempted et
le second appel répète le classement sans apporter d’information utile.

**Observation Logfire et tool SQL :** la trace confirme deux appels
au tool SQL et trois appels au modèle. La recherche FAISS dure
263 ms et le pipeline environ 5,18 secondes. Les deux exécutions
SQL durent environ 1,75 seconde et 692 ms.

**Métriques :** la fidélité de 1,00 confirme que la réponse est
soutenue par les résultats SQL. La pertinence est de 0,81 et
la précision des contextes de 0,59. L’exactitude factuelle de 0,22
paraît sévère au regard des noms et pourcentages corrects :
l’omission des tentatives est réelle, mais ne suffit pas à expliquer
ce score sans examiner les jugements détaillés de RAGAS.

**Pistes d’amélioration à tester :**
- Récupérer et afficher le nombre de tentatives avec les pourcentages.
- Éviter les appels SQL répétés lorsqu’un résultat suffit.
- Réduire les contextes FAISS inutiles pour les classements statistiques.
- Examiner les jugements de RAGAS pour comprendre le faible score
  d’exactitude factuelle.

### Analyse Question 4

In [11]:
row = results_V03.loc[
    results_V03["case_id"] == "numeric_complex_01"
].iloc[0]

print("QUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Parmi les joueurs ayant tenté au moins 100 tirs à trois points, lequel possède le meilleur pourcentage de réussite ?

RÉPONSE ATTENDUE :
Seth Curry possède le meilleur pourcentage de réussite parmi les joueurs ayant tenté au moins 100 tirs à trois points, avec 45,6 % sur 184 tentatives.

RÉPONSE OBTENUE :
Seth Curry détient le meilleur pourcentage de réussite aux tirs à trois points parmi les joueurs ayant tenté au moins 100 tirs à trois points en saison 2024-25, avec un **45,6 %**.

*(Aucune URL n'est disponible pour ce joueur.)*

------------------------------ CONTEXTE 1 ------------------------------

27                      TD3            Triple-doubles (≥10 dans trois catégories principales)
28                    + / -  Plus-Minus (écart de score lorsque le joueur est sur le terrain)
29                   OFFRTG             Offensive Rating (points marqués par 100 possessions)
30                   DEFRTG           Defensive Rating (points encaissés par 100 possessions)
31                   NETRTG                                      Net Rating = OFFRTG - DEFRTG
32                     AST%     Pourcentage d'assists – implication dans les passes décisives
33                   AST/TO                                    Ratio passes / pertes de balle
34                AST RATIO                              Ratio d’assists pour 100 possessions
35                    OREB%           Pourcentage de rebonds offensifs parmi ceux disponibles
36                    DREB%                                                  Idem en défensif
37                     REB%              Pourcentage de rebonds totaux parmi ceux disponibles
38                 TO RATIO              Turnover Ratio – pertes de balle par 100 possessions
39                     EFG%                     Effective Field Goal % (pondère les 3 points)
40                      TS%               True Shooting % (inclut FG et FT dans l'efficacité)
41                     USG%                Usage Rate – % des actions utilisées par le joueur

------------------------------ CONTEXTE 2 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
86                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
87                                             Players    Nombre de point total                          FGM       Pourcentage de tirs réussis  Pourcentage de réussite aux tirs à 3 points  Pourcentage de réussite aux lancers francs  Rebonds offensifs  Estimation de l’impact du joueur
88                             Shai Gilgeous-Alexander                     2485                          859                              51.9                                         37.5                                        89.8                 68                              19.9

------------------------------ CONTEXTE 3 ------------------------------

Dictionnaire des données                                                        Unnamed: 1
0                    Player                                                     Nom du joueur
1                      Team                               Équipe du joueur (code à 3 lettres)
2                       Age                                                     Âge du joueur
3                        GP                             Nombre de matchs joués (Games Played)
4                         W             Nombre de victoires de l'équipe lors des matchs joués
5                         L                                                Nombre de défaites
6                       Min                                 Minutes moyennes jouées par match
7                       PTS                               Points marqués en moyenne par match
8                       FGM                         Tirs réussis par match (Field Goals Made)
9                       FGA                     Tirs tentés par match (Field Goals Attempted)
10                      FG%                                  Pourcentage de réussite aux tirs
11                 15:00:00                                 Minutes jouées après 15:00 de jeu
12                      3PA                                  Tirs à 3 points tentés par match
13                      3P%                                Pourcentage de réussite à 3 points

------------------------------ CONTEXTE 4 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
86                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
87                                             Players    Nombre de point total                          FGM       Pourcentage de tirs réussis  Pourcentage de réussite aux tirs à 3 points  Pourcentage de réussite aux lancers francs  Rebonds offensifs  Estimation de l’impact du joueur
88                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN

------------------------------ CONTEXTE 5 ------------------------------

itself as well.)
Répondre
False_Pear1860
~10j
What is this table sorted by?? Though it was crazy that
was so far down the list, but then realized he
should be like 3rd place if sorted by rTS
Répondre
LQ
Akipella
~10j
Comm. du top 1%
fixed it
4 3
Répondre
Zazi751
-10j
If you don't also provide how rTS is calculated then the whole list is garbage. Some of these guys played
through multiple eras with significant shifts
Répondre
ijoeblow
~10 j
Wow,
though DWade would be #1 seeing how he was gifted 503,244 free throws in the 2006 playoffs.
Répondre
Artimusjones88
-10j
How many All NBA selections? First teams? He was never a top 4 guard. Good PR
4
Répondre
Nolofinwe_2782
-10j
He's one of the most overrated players of all time
Now if he played in this era? 25 ppg probably
Répondre
notatowel42o
-10 j
Reggie is one of the most overrated players of all time. You remove that Knicks series he would be a
forgotten player.
Répondre
Icy-Role-6333
-10j
https:llwww reddit.comlrInbalcomments/1l161bplreggie
miller_is
the_most_efficient_first
30/36
Curry
They
optionl
12/06/2025 13:11
Reggie Miller is the most efficient first option in NBA playoff history
rInba
Accéder au contenu principal
Se connecter
So efficient he never won the playoffs
Répondre
Javd318
~7j
Really illuminates how useless efficiency is as a metric
Répondre
imperialmoose
-10 j
Interesting little set of stats! Regarding that last sentence; you're not accounting for all sorts of parts of

------------------------------ CONTEXTE 6 ------------------------------

Source : tool SQL NBA, saison 2024-25.
{"status": "ok", "sql": "SELECT p.player_name, s.three_point_pct\nFROM stats AS s\nJOIN players AS p ON p.player_id = s.player_id\nJOIN reports AS r ON r.report_id = s.report_id\nWHERE r.season = '2024-25' AND s.three_points_attempted >= 100\nAND s.three_point_pct IS NOT NULL\nORDER BY s.three_point_pct DESC, p.player_name ASC\nLIMIT 1", "columns": ["player_name", "three_point_pct"], "rows": [{"player_name": "Seth Curry", "three_point_pct": 45.6}], "truncated": false, "count": 1}

### Cas numeric_complex_01 — Pourcentage à trois points avec au moins 100 tentatives

![Trace Logfire de la question 4](logfire/Logfire_question_4.png)

**Résultat :** Seth Curry et son pourcentage de 45,6 % sont
correctement identifiés. Les 184 tentatives mentionnées dans
la référence ne sont pas précisées.

**Contextes récupérés :** les cinq passages FAISS ne permettent
pas de répondre à la question. Le résultat SQL fournit directement
le joueur et son pourcentage, après application du filtre demandé.

**Réponse :** elle restitue correctement le résultat SQL.
Cependant, la remarque sur l’absence d’URL est inutile et
non justifiée : la requête ne sélectionne pas player_url.
Une colonne non récupérée ne signifie pas que la donnée est absente.

**Diagnostic :** la requête utilise correctement
three_points_attempted >= 100, trie three_point_pct par ordre
décroissant et limite le résultat à un joueur. Le calcul répond
donc à la demande, mais les colonnes sélectionnées ne permettent
pas de préciser le nombre de tentatives.

**Observation Logfire et tool SQL :** la trace confirme un seul
appel au tool SQL et deux appels au modèle. La recherche FAISS
dure 243 ms, l’exécution du tool environ 2,81 secondes et
le pipeline environ 9,20 secondes.

**Métriques :** la pertinence de 0,84 concorde avec une réponse
qui répond à la question. La fidélité de 0,67 peut être affectée
par la remarque non étayée sur l’URL, sans que cette cause soit
confirmée. La précision des contextes est de 0,17.
L’exactitude factuelle de 0,00 ne reflète pas les deux éléments
corrects observés : le joueur et son pourcentage. Les jugements
détaillés du juge seraient nécessaires pour expliquer ce score.

**Pistes d’amélioration à tester :**
- Sélectionner le nombre de tentatives pour contextualiser le résultat.
- Ne mentionner les liens que lorsqu’ils sont demandés.
- Ne pas déclarer une donnée absente lorsqu’elle n’a pas été récupérée.
- Réduire les contextes FAISS inutiles pour les questions statistiques.
- Examiner les jugements RAGAS lorsque les scores divergent
  de la vérification humaine.

### Analyse questio 5

In [12]:
row = results_V03.loc[
    results_V03["case_id"] == "numeric_complex_02"
].iloc[0]

print("QUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Quels sont les cinq joueurs ayant marqué le plus de points, classés du premier au cinquième ?

RÉPONSE ATTENDUE :
Les cinq joueurs ayant marqué le plus de points sont Shai Gilgeous-Alexander avec 2 485 points, Anthony Edwards avec 2 180 points, Nikola Jokić avec 2 072 points, Giannis Antetokounmpo avec 2 037 points et Jayson Tatum avec 1 930 points, dans cet ordre.

RÉPONSE OBTENUE :
Voici les cinq joueurs ayant marqué le plus de points lors de la saison 2024-25 :

| Rang | Joueur                     | Nombre de points totaux |
|------|----------------------------|--------------------------|
| 1    | Shai Gilgeous-Alexander     | 2 485                    |
| 2    | Anthony Edwards            | 2 180                    |
| 3    | Nikola Jokić                | 2 072                    |
| 4    | Giannis Antetokounmpo      | 2 037                    |
| 5    | Jayson Tatum               | 1 930                    |

------------------------------ CONTEXTE 1 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
86                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
87                                             Players    Nombre de point total                          FGM       Pourcentage de tirs réussis  Pourcentage de réussite aux tirs à 3 points  Pourcentage de réussite aux lancers francs  Rebonds offensifs  Estimation de l’impact du joueur
88                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN

------------------------------ CONTEXTE 2 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
86                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
87                                             Players    Nombre de point total                          FGM       Pourcentage de tirs réussis  Pourcentage de réussite aux tirs à 3 points  Pourcentage de réussite aux lancers francs  Rebonds offensifs  Estimation de l’impact du joueur
88                             Shai Gilgeous-Alexander                     2485                          859                              51.9                                         37.5                                        89.8                 68                              19.9

------------------------------ CONTEXTE 3 ------------------------------

Dictionnaire des données                                                        Unnamed: 1
0                    Player                                                     Nom du joueur
1                      Team                               Équipe du joueur (code à 3 lettres)
2                       Age                                                     Âge du joueur
3                        GP                             Nombre de matchs joués (Games Played)
4                         W             Nombre de victoires de l'équipe lors des matchs joués
5                         L                                                Nombre de défaites
6                       Min                                 Minutes moyennes jouées par match
7                       PTS                               Points marqués en moyenne par match
8                       FGM                         Tirs réussis par match (Field Goals Made)
9                       FGA                     Tirs tentés par match (Field Goals Attempted)
10                      FG%                                  Pourcentage de réussite aux tirs
11                 15:00:00                                 Minutes jouées après 15:00 de jeu
12                      3PA                                  Tirs à 3 points tentés par match
13                      3P%                                Pourcentage de réussite à 3 points

------------------------------ CONTEXTE 4 ------------------------------

13                      3P%                                Pourcentage de réussite à 3 points
14                      FTM                         Lancers francs réussis (Free Throws Made)
15                      FTA                                             Lancers francs tentés
16                      FT%                        Pourcentage de réussite aux lancers francs
17                     OREB                                                 Rebonds offensifs
18                     DREB                                                 Rebonds défensifs
19                      REB                                                    Rebonds totaux
20                      AST                                        Passes décisives (Assists)
21                      TOV                                        Balles perdues (Turnovers)
22                      STL                                            Interceptions (Steals)
23                      BLK                                                  Contres (Blocks)
24                       PF                                               Fautes personnelles
25                       FP                                                    Fantasy Points
26                      DD2             Double-doubles (≥10 dans deux catégories principales)
27                      TD3            Triple-doubles (≥10 dans trois catégories principales)

------------------------------ CONTEXTE 5 ------------------------------

27                      TD3            Triple-doubles (≥10 dans trois catégories principales)
28                    + / -  Plus-Minus (écart de score lorsque le joueur est sur le terrain)
29                   OFFRTG             Offensive Rating (points marqués par 100 possessions)
30                   DEFRTG           Defensive Rating (points encaissés par 100 possessions)
31                   NETRTG                                      Net Rating = OFFRTG - DEFRTG
32                     AST%     Pourcentage d'assists – implication dans les passes décisives
33                   AST/TO                                    Ratio passes / pertes de balle
34                AST RATIO                              Ratio d’assists pour 100 possessions
35                    OREB%           Pourcentage de rebonds offensifs parmi ceux disponibles
36                    DREB%                                                  Idem en défensif
37                     REB%              Pourcentage de rebonds totaux parmi ceux disponibles
38                 TO RATIO              Turnover Ratio – pertes de balle par 100 possessions
39                     EFG%                     Effective Field Goal % (pondère les 3 points)
40                      TS%               True Shooting % (inclut FG et FT dans l'efficacité)
41                     USG%                Usage Rate – % des actions utilisées par le joueur

------------------------------ CONTEXTE 6 ------------------------------

Source : tool SQL NBA, saison 2024-25.
{"status": "ok", "sql": "SELECT p.player_name, s.points_total\nFROM stats AS s\nJOIN players AS p ON p.player_id = s.player_id\nJOIN reports AS r ON r.report_id = s.report_id\nWHERE r.season = '2024-25' AND s.points_total IS NOT NULL\nORDER BY s.points_total DESC, p.player_name ASC\nLIMIT 5", "columns": ["player_name", "points_total"], "rows": [{"player_name": "Shai Gilgeous-Alexander", "points_total": 2485.0}, {"player_name": "Anthony Edwards", "points_total": 2180.0}, {"player_name": "Nikola Jokić", "points_total": 2072.0}, {"player_name": "Giannis Antetokounmpo", "points_total": 2037.0}, {"player_name": "Jayson Tatum", "points_total": 1930.0}], "truncated": false, "count": 5}

### Cas numeric_complex_02 — Classement des cinq meilleurs marqueurs

![Trace Logfire de la question 5](logfire/Logfire_question_5.png)

**Résultat :** les cinq joueurs, leurs totaux de points et leur
ordre correspondent exactement à la réponse attendue.

**Contextes récupérés :** les passages FAISS ne fournissent pas
le classement complet. Seul le contexte 2 donne un total utile :
2 485 points pour Shai Gilgeous-Alexander. Le résultat SQL contient
les cinq joueurs et toutes les valeurs nécessaires.

**Réponse :** le tableau restitue correctement les résultats SQL,
avec des rangs explicites et une unité claire. Aucun ajout inutile
ni affirmation non étayée n’est observé.

**Diagnostic :** la requête sélectionne correctement points_total,
filtre la saison 2024-25 et applique un tri décroissant avec LIMIT 5.
Le tool SQL fournit une réponse complète malgré des passages FAISS
peu utiles. Le dictionnaire décrit les points comme une moyenne,
alors que le tableau et les valeurs SQL correspondent ici à des
totaux : cette incohérence documentaire reste à clarifier.

**Observation Logfire et tool SQL :** la trace confirme un seul
appel au tool SQL et deux appels au modèle. La recherche FAISS
dure 689 ms et le tool SQL environ 1,03 seconde. Le pipeline dure
19,6 secondes, dont 17,3 secondes pour le dernier appel au modèle.
L’essentiel du temps est donc consacré à cet appel, sans que
la trace permette d’en déterminer la cause.

**Métriques :** la fidélité et l’exactitude factuelle de 1,00
concordent avec la vérification humaine. La pertinence est de 0,82.
La précision des contextes de 0,17 est cohérente avec une preuve
SQL placée en dernier parmi six contextes, dont plusieurs sont
peu utiles pour répondre.

**Pistes d’amélioration à tester :**
- Réduire les passages FAISS inutiles pour les classements statistiques.
- Clarifier les définitions contradictoires entre le dictionnaire
  Excel et les données importées.
- Comparer les durées sur plusieurs exécutions pour vérifier
  si la lenteur du dernier appel au modèle se répète.
- Conserver ce cas pour vérifier que les prochaines modifications
  préservent un classement complet et correct.

### Analyse Question 6

In [13]:
row = results_V03.loc[
    results_V03["case_id"] == "comparison_01"
].iloc[0]

print("QUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Compare le nombre total de rebonds de Shai Gilgeous-Alexander et d’Anthony Edwards.

RÉPONSE ATTENDUE :
Shai Gilgeous-Alexander totalise 380 rebonds, contre 450 pour Anthony Edwards. Anthony Edwards a donc capté 70 rebonds de plus.

RÉPONSE OBTENUE :
En saison 2024-25, **Shai Gilgeous-Alexander** a marqué **380 rebonds totaux**, tandis qu'**Anthony Edwards** en a totalisé **450 rebonds** pour la même saison.

------------------------------ CONTEXTE 1 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
86                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
87                                             Players    Nombre de point total                          FGM       Pourcentage de tirs réussis  Pourcentage de réussite aux tirs à 3 points  Pourcentage de réussite aux lancers francs  Rebonds offensifs  Estimation de l’impact du joueur
88                             Shai Gilgeous-Alexander                     2485                          859                              51.9                                         37.5                                        89.8                 68                              19.9

------------------------------ CONTEXTE 2 ------------------------------

27                      TD3            Triple-doubles (≥10 dans trois catégories principales)
28                    + / -  Plus-Minus (écart de score lorsque le joueur est sur le terrain)
29                   OFFRTG             Offensive Rating (points marqués par 100 possessions)
30                   DEFRTG           Defensive Rating (points encaissés par 100 possessions)
31                   NETRTG                                      Net Rating = OFFRTG - DEFRTG
32                     AST%     Pourcentage d'assists – implication dans les passes décisives
33                   AST/TO                                    Ratio passes / pertes de balle
34                AST RATIO                              Ratio d’assists pour 100 possessions
35                    OREB%           Pourcentage de rebonds offensifs parmi ceux disponibles
36                    DREB%                                                  Idem en défensif
37                     REB%              Pourcentage de rebonds totaux parmi ceux disponibles
38                 TO RATIO              Turnover Ratio – pertes de balle par 100 possessions
39                     EFG%                     Effective Field Goal % (pondère les 3 points)
40                      TS%               True Shooting % (inclut FG et FT dans l'efficacité)
41                     USG%                Usage Rate – % des actions utilisées par le joueur

------------------------------ CONTEXTE 3 ------------------------------

13                      3P%                                Pourcentage de réussite à 3 points
14                      FTM                         Lancers francs réussis (Free Throws Made)
15                      FTA                                             Lancers francs tentés
16                      FT%                        Pourcentage de réussite aux lancers francs
17                     OREB                                                 Rebonds offensifs
18                     DREB                                                 Rebonds défensifs
19                      REB                                                    Rebonds totaux
20                      AST                                        Passes décisives (Assists)
21                      TOV                                        Balles perdues (Turnovers)
22                      STL                                            Interceptions (Steals)
23                      BLK                                                  Contres (Blocks)
24                       PF                                               Fautes personnelles
25                       FP                                                    Fantasy Points
26                      DD2             Double-doubles (≥10 dans deux catégories principales)
27                      TD3            Triple-doubles (≥10 dans trois catégories principales)

------------------------------ CONTEXTE 4 ------------------------------

41                     USG%                Usage Rate – % des actions utilisées par le joueur
42                     PACE                        Rythme de jeu (possessions par 48 minutes)
43                      PIE           Player Impact Estimate – évaluation globale de l’impact
44                     POSS                                Nombre total de possessions jouées

------------------------------ CONTEXTE 5 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
86                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
87                                             Players    Nombre de point total                          FGM       Pourcentage de tirs réussis  Pourcentage de réussite aux tirs à 3 points  Pourcentage de réussite aux lancers francs  Rebonds offensifs  Estimation de l’impact du joueur
88                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN

------------------------------ CONTEXTE 6 ------------------------------

Source : tool SQL NBA, saison 2024-25.
{"status": "ok", "sql": "SELECT p.player_name, s.total_rebounds\nFROM stats AS s\nJOIN players AS p ON p.player_id = s.player_id\nJOIN reports AS r ON r.report_id = s.report_id\nWHERE r.season = '2024-25'\nAND p.player_name IN ('Shai Gilgeous-Alexander', 'Anthony Edwards')\nAND s.total_rebounds IS NOT NULL", "columns": ["player_name", "total_rebounds"], "rows": [{"player_name": "Anthony Edwards", "total_rebounds": 450.0}, {"player_name": "Shai Gilgeous-Alexander", "total_rebounds": 380.0}], "truncated": false, "count": 2}

### Cas comparison_01 — Comparaison des rebonds de deux joueurs

![Trace Logfire de la question 6](logfire/Logfire_question_6.png)

**Résultat :** les deux totaux sont corrects : 380 rebonds pour
Shai Gilgeous-Alexander et 450 pour Anthony Edwards.
La différence de 70 rebonds n’est pas explicitée.

**Contextes récupérés :** les cinq passages FAISS ne fournissent
pas les deux totaux nécessaires. Le contexte 1 mentionne seulement
les rebonds offensifs de Shai Gilgeous-Alexander. Le résultat SQL
fournit les rebonds totaux des deux joueurs.

**Réponse :** elle restitue correctement les valeurs, mais juxtapose
les totaux sans préciser qu’Anthony Edwards a capté 70 rebonds
de plus. La formulation « a marqué des rebonds » est maladroite :
« a capté » ou « a totalisé » serait plus adapté.

**Diagnostic :** la requête utilise correctement total_rebounds,
sélectionne les deux joueurs et filtre la saison 2024-25.
La récupération fonctionne ; l’amélioration concerne surtout
la formulation et l’explicitation de la comparaison.

**Observation Logfire et tool SQL :** la trace confirme un seul
appel au tool SQL et deux appels au modèle. La recherche FAISS
dure 379 ms, le tool SQL environ 774 ms et le pipeline
environ 2,23 secondes.

**Métriques :** l’exactitude factuelle de 1,00 confirme les valeurs
correctes, mais ne traduit pas l’omission de l’écart attendu.
La pertinence est de 0,86 et la précision des contextes de 0,17.
La fidélité est manquante à cause d’une erreur de calcul du juge ;
cela ne permet pas de conclure à un défaut de fidélité.

**Pistes d’amélioration à tester :**
- Pour une comparaison, préciser qui possède la valeur la plus
  élevée et calculer l’écart.
- Employer un vocabulaire adapté aux statistiques concernées.
- Réduire les passages FAISS inutiles pour les questions statistiques.
- Compléter les métriques par une vérification humaine
  de la complétude de la réponse.

### Analyse question 7

In [14]:
row = results_V03.loc[
    results_V03["question"].str.contains(
        "pourcentaj", case=False, na=False
    )
].iloc[0]

print("\nQUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
c ki les joueur ki on le meilleur pourcentaj a 3 points ?

RÉPONSE ATTENDUE :
Alondes Williams et Skal Labissiere possèdent le meilleur pourcentage de réussite à trois points avec 100 %, chacun sur une seule tentative.

RÉPONSE OBTENUE :
Voici les cinq joueurs avec le pourcentage de réussite aux tirs à 3 points le plus élevé pour la saison 2024-25 :

| Rang | Joueur                     | 3P%   |
|------|-----------------------------|-------|
| 1    | Alondes Williams             | 100%  |
| 2    | Skal Labissiere             | 100%  |
| 3    | PJ Dozier                   | 66,7% |
| 4    | Patrick Baldwin Jr.        | 56,5% |
| 5    | Dru Smith                   | 53,3% |

Pour plus de détails sur leur performance ou leur équipe, je peux fournir des liens vers leurs fiches NBA si nécessaire.

------------------------------ CONTEXTE 1 ------------------------------

41                     USG%                Usage Rate – % des actions utilisées par le joueur
42                     PACE                        Rythme de jeu (possessions par 48 minutes)
43                      PIE           Player Impact Estimate – évaluation globale de l’impact
44                     POSS                                Nombre total de possessions jouées

------------------------------ CONTEXTE 2 ------------------------------

27                      TD3            Triple-doubles (≥10 dans trois catégories principales)
28                    + / -  Plus-Minus (écart de score lorsque le joueur est sur le terrain)
29                   OFFRTG             Offensive Rating (points marqués par 100 possessions)
30                   DEFRTG           Defensive Rating (points encaissés par 100 possessions)
31                   NETRTG                                      Net Rating = OFFRTG - DEFRTG
32                     AST%     Pourcentage d'assists – implication dans les passes décisives
33                   AST/TO                                    Ratio passes / pertes de balle
34                AST RATIO                              Ratio d’assists pour 100 possessions
35                    OREB%           Pourcentage de rebonds offensifs parmi ceux disponibles
36                    DREB%                                                  Idem en défensif
37                     REB%              Pourcentage de rebonds totaux parmi ceux disponibles
38                 TO RATIO              Turnover Ratio – pertes de balle par 100 possessions
39                     EFG%                     Effective Field Goal % (pondère les 3 points)
40                      TS%               True Shooting % (inclut FG et FT dans l'efficacité)
41                     USG%                Usage Rate – % des actions utilisées par le joueur

------------------------------ CONTEXTE 3 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
86                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
87                                             Players    Nombre de point total                          FGM       Pourcentage de tirs réussis  Pourcentage de réussite aux tirs à 3 points  Pourcentage de réussite aux lancers francs  Rebonds offensifs  Estimation de l’impact du joueur
88                             Shai Gilgeous-Alexander                     2485                          859                              51.9                                         37.5                                        89.8                 68                              19.9

------------------------------ CONTEXTE 4 ------------------------------

Dictionnaire des données                                                        Unnamed: 1
0                    Player                                                     Nom du joueur
1                      Team                               Équipe du joueur (code à 3 lettres)
2                       Age                                                     Âge du joueur
3                        GP                             Nombre de matchs joués (Games Played)
4                         W             Nombre de victoires de l'équipe lors des matchs joués
5                         L                                                Nombre de défaites
6                       Min                                 Minutes moyennes jouées par match
7                       PTS                               Points marqués en moyenne par match
8                       FGM                         Tirs réussis par match (Field Goals Made)
9                       FGA                     Tirs tentés par match (Field Goals Attempted)
10                      FG%                                  Pourcentage de réussite aux tirs
11                 15:00:00                                 Minutes jouées après 15:00 de jeu
12                      3PA                                  Tirs à 3 points tentés par match
13                      3P%                                Pourcentage de réussite à 3 points

------------------------------ CONTEXTE 5 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
86                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
87                                             Players    Nombre de point total                          FGM       Pourcentage de tirs réussis  Pourcentage de réussite aux tirs à 3 points  Pourcentage de réussite aux lancers francs  Rebonds offensifs  Estimation de l’impact du joueur
88                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN

------------------------------ CONTEXTE 6 ------------------------------

Source : tool SQL NBA, saison 2024-25.
{"status": "ok", "sql": "SELECT\n    p.player_name,\n    s.three_point_pct\nFROM\n    stats s\nJOIN\n    players p ON p.player_id = s.player_id\nJOIN\n    reports r ON r.report_id = s.report_id\nWHERE\n    r.season = '2024-25'\n    AND s.three_point_pct IS NOT NULL\nORDER BY\n    s.three_point_pct DESC, p.player_name ASC\nLIMIT 5", "columns": ["player_name", "three_point_pct"], "rows": [{"player_name": "Alondes Williams", "three_point_pct": 100.0}, {"player_name": "Skal Labissiere", "three_point_pct": 100.0}, {"player_name": "PJ Dozier", "three_point_pct": 66.7}, {"player_name": "Patrick Baldwin Jr,", "three_point_pct": 56.5}, {"player_name": "Dru Smith", "three_point_pct": 53.3}], "truncated": false, "count": 5}

### Cas bruité — Meilleur pourcentage à trois points

![Trace Logfire de la question 7](logfire/Logfire_question_7.png)

**Résultat :** malgré les fautes et les abréviations, les deux
joueurs attendus sont correctement identifiés à 100 %.
La précision « une seule tentative chacun » est absente.

**Contextes récupérés :** les cinq passages FAISS ne permettent
pas d’établir le classement. Le résultat SQL fournit les cinq
joueurs et leurs pourcentages, correctement repris dans le tableau.

**Réponse :** elle répond à l’intention de la question sans demander
de reformulation. Elle ajoute cependant une proposition de liens
non demandée et ne contextualise pas les 100 % par le nombre
de tentatives.

**Diagnostic :** la formulation bruitée est correctement comprise.
La requête utilise three_point_pct et un tri décroissant.
Le classement correspond à celui obtenu pour la question bien
orthographiée, mais three_points_attempted n’est pas sélectionné.

**Observation Logfire et tool SQL :** la trace confirme un seul
appel au tool SQL et deux appels au modèle. La recherche FAISS
dure 287 ms, le tool SQL environ 1,33 seconde et le pipeline
environ 4,20 secondes.

**Métriques :** la fidélité de 0,86 et la pertinence de 0,71
indiquent une réponse largement soutenue et pertinente.
La précision des contextes est de 0,17. L’exactitude factuelle
de 0,00 contraste avec les noms et pourcentages corrects :
l’omission des tentatives est réelle, mais les jugements détaillés
seraient nécessaires pour expliquer ce score.

**Pistes d’amélioration à tester :**
- Récupérer le nombre de tentatives pour contextualiser les pourcentages.
- Supprimer les propositions de liens lorsqu’ils ne sont pas demandés.
- Réduire les passages FAISS inutiles pour les classements statistiques.
- Étendre les tests à d’autres formulations bruitées pour vérifier
  que cette bonne compréhension se maintient.

In [15]:
row = results_V03.loc[
    results_V03["question"].str.contains(
        "Toulouse", case=False, na=False
    )
].iloc[0]

print("\nQUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Quel temps fera-t-il demain à Toulouse ?

RÉPONSE ATTENDUE :
Je ne dispose pas de données météorologiques permettant de répondre à cette question.

RÉPONSE OBTENUE :
Je ne peux pas répondre à cette question, car elle ne concerne pas les statistiques NBA de la saison 2024-25 ni les données disponibles dans les contextes fournis.

------------------------------ CONTEXTE 1 ------------------------------

34                                                 MEM                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
35                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
36                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
37                                Analyse d'une équipe                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
38                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN

------------------------------ CONTEXTE 2 ------------------------------

129                       Analyse(s) complémentaire(s)                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN

------------------------------ CONTEXTE 3 ------------------------------

129                       Analyse(s) complémentaire(s)                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN

------------------------------ CONTEXTE 4 ------------------------------

Dictionnaire des données                                                        Unnamed: 1
0                    Player                                                     Nom du joueur
1                      Team                               Équipe du joueur (code à 3 lettres)
2                       Age                                                     Âge du joueur
3                        GP                             Nombre de matchs joués (Games Played)
4                         W             Nombre de victoires de l'équipe lors des matchs joués
5                         L                                                Nombre de défaites
6                       Min                                 Minutes moyennes jouées par match
7                       PTS                               Points marqués en moyenne par match
8                       FGM                         Tirs réussis par match (Field Goals Made)
9                       FGA                     Tirs tentés par match (Field Goals Attempted)
10                      FG%                                  Pourcentage de réussite aux tirs
11                 15:00:00                                 Minutes jouées après 15:00 de jeu
12                      3PA                                  Tirs à 3 points tentés par match
13                      3P%                                Pourcentage de réussite à 3 points

------------------------------ CONTEXTE 5 ------------------------------

4 -1
Répondre
twrs_29
~15 j
Comm; du
19
turkmileymileyturk
~15j
https://www reddit.comirinbalcommentsl 1kxixihlhow
is_it_that
the_two
best_teams
the
playoffsl
13/23
ring
top
12/06/2025 13.09
How is it that the two best teams in the
playoffs based on stats
having
chance of playing against each other in the Finals, is
Accéder au contenu principal
Se connecter
Now add to the fact that both teams are the most complete in the NBA and both have a superstar
pg that takes over games
anybody crying about this finals series should just stop watching
basketball. Stick to NFL where rivalries are more important than the game itself. Real fans of
basketball are about the game not the
or social media presence.
0
Répondre
ShowdownValue
~15 j
It definitely will be. It always is
Répondre
SemataryPolka
~15 j
The foul baiting will make the Pacers fans toxic towards you: Minimum four games of Caruso
assaulting people with no call and SGA falling and getting
a foul from the wind will do it. Just ask
any fanbase that's played the thunder this post season
Répondre
UmphreysMcGee
-14 j
Shai had 4 FT attempts tonight and your team lost by 30.
think dogs are just afraid of Thunder.
Répondre
réponse supplémentaire
Miserable_Lead_9828
~15 j
Comm. du top 1%
highly doubt it'Il be toxic outside of all the neutrals who are hate
watching
10
Répondre
MuchAbouAboutNothing
~15 j
Comm. du
1%
Not even going to be toxic outside of r/nba. Most of my basketball fans have been having a blast all

### Cas hors périmètre — Météo à Toulouse

![Trace Logfire de la question 8](logfire/Logfire_question_8.png)

**Résultat :** l’agent refuse correctement de fournir une prévision
météorologique. Aucune information météo n’est inventée.

**Contextes récupérés :** les cinq passages sont hors sujet.
Certains contiennent principalement des cellules vides, deux
sont identiques et aucun ne fournit de données météorologiques.

**Réponse :** le refus est adapté et cohérent avec la réponse
attendue. Sa justification pourrait être plus directe :
« Je ne dispose pas de données météorologiques. »
Le périmètre annoncé est trop restrictif, puisque l’assistant
traite aussi les commentaires des supporters.

**Diagnostic :** le respect du périmètre fonctionne dans la réponse
finale. Cependant, une recherche documentaire est effectuée
pour une question sans rapport avec les données disponibles.

**Observation Logfire et tool SQL :** la trace confirme une recherche
FAISS de 304 ms et un seul appel au modèle de 564 ms,
sans appel au tool SQL. Le pipeline dure environ 886 ms.
L’absence d’appel SQL est adaptée ; la recherche FAISS pourrait
être évitée par une détection préalable du hors périmètre.

**Métriques :** la pertinence et la précision des contextes sont
nulles, la fidélité vaut 0,60 et l’exactitude factuelle 0,33.
Ces scores ne suffisent pas à qualifier le refus d’échec :
l’évaluation humaine confirme un comportement adapté.
Ce cas doit aussi être évalué sur la capacité à refuser
sans inventer de réponse.

**Pistes d’amélioration à tester :**
- Détecter les questions hors périmètre avant la recherche FAISS.
- Formuler un refus court, centré sur les données indisponibles.
- Décrire le périmètre comme les statistiques NBA et les commentaires
  des supporters.
- Évaluer séparément les refus justifiés dans la grille humaine.

### Conclusion générale — Évaluation de la V03

L’analyse des huit questions montre que le tool SQL fournit des
résultats fiables pour les questions statistiques de ce jeu de test.
Les joueurs, les valeurs et les classements obtenus correspondent
aux éléments attendus. Le filtre des 100 tentatives est correctement
appliqué et la question comportant des fautes est bien comprise.

Les réponses restent parfois incomplètes : le nombre de tentatives
n’est pas précisé pour les pourcentages à trois points et l’écart
de 70 rebonds n’est pas explicité dans la comparaison. Des ajouts
inutiles subsistent également, notamment les propositions de liens
et l’affirmation non justifiée qu’une URL est indisponible.

**La recherche documentaire constitue la principale limite observée.**
Les passages FAISS sont souvent peu utiles pour les statistiques.
Pour les commentaires des supporters, ils sont soit hors sujet,
soit concentrés sur un seul fil Reddit. Ils ne permettent donc
pas toujours de couvrir les débats attendus. Un classement global
des joueurs par fréquence de mention nécessite également un
comptage du corpus, que la recherche de cinq extraits ne garantit pas.

**Logfire confirme une utilisation adaptée du tool SQL :**
il est appelé pour les cinq questions statistiques, mais pas pour
les commentaires ou la météo. Un appel SQL redondant est observé
sur une question. Les durées varient d’environ 0,89 à 29 secondes ;
les exécutions les plus lentes sont principalement dominées
par les appels au modèle.

**Les métriques RAGAS doivent être croisées avec l’analyse humaine.**
Certains scores d’exactitude factuelle sont faibles malgré des
noms et des valeurs corrects. À l’inverse, un score de 1,00 ne
signale pas toujours une omission dans la réponse. Deux scores
de fidélité sont manquants à cause d’erreurs du juge.
Le refus de répondre à la météo est adapté malgré des scores faibles.

La V03 présente donc des résultats statistiques convaincants sur
les cas testés, mais conserve des limites de recherche documentaire,
de complétude et de formulation. La comparaison avec la V01 reste
nécessaire pour mesurer précisément l’amélioration ; ces huit cas
ne suffisent pas à généraliser la fiabilité à toutes les questions.

**Priorités d’amélioration à tester :**
- Adapter les sources à la question : SQL pour les statistiques,
  documents Reddit pour les commentaires.
- Diversifier et nettoyer les passages documentaires récupérés.
- Compléter les réponses avec les tentatives ou les écarts utiles.
- Supprimer les remarques sur les liens lorsqu’ils ne sont pas demandés
  et éviter de déclarer absente une donnée non récupérée.
- Clarifier les incohérences du dictionnaire Excel et prévoir
  un comptage pour les questions de fréquence.
- Éviter les appels redondants et détecter le hors périmètre
  avant la recherche.

## Comparaison V01 / V03 — Effet de l’intégration du tool SQL

Les mêmes huit questions ont été utilisées pour les deux versions.
La comparaison porte sur l’exactitude des réponses, leur complétude
et leur justification par les données disponibles.

### Comparaison des réponses par cas

| Cas | V01 | V03 | Évolution observée |
|---|---|---|---|
| Joueurs les plus mentionnés | Classement incorrect, accompagné d’informations inventées. | Abstention face à des contextes insuffisants. | Moins d’inventions, mais la question reste sans réponse. |
| Principaux sujets de débat | Quelques thèmes corrects, mais plusieurs omissions et ajouts non étayés. | Plusieurs thèmes soutenus par les extraits, mais couverture toujours incomplète. | Meilleure fidélité aux extraits ; diversité documentaire encore insuffisante. |
| Meilleur pourcentage à trois points | Joueurs et pourcentages incorrects. | Alondes Williams et Skal Labissiere correctement identifiés à 100 %. | Amélioration nette ; le nombre de tentatives manque. |
| Meilleur pourcentage avec au moins 100 tentatives | Reggie Miller cité à tort avec 43,4 %. | Seth Curry correctement identifié à 45,6 %, avec le filtre SQL demandé. | Amélioration nette ; les 184 tentatives sont omises et la remarque sur l’URL est injustifiée. |
| Cinq meilleurs marqueurs | Classement incorrect et confusion entre totaux et moyennes. | Les cinq joueurs, les totaux et l’ordre sont corrects. | Réponse entièrement conforme à la référence. |
| Comparaison des rebonds | Totaux inventés et conclusion inversée. | Totaux corrects : 380 et 450 rebonds. | Amélioration nette ; l’écart de 70 rebonds reste implicite. |
| Question avec fautes | Intention comprise, mais classement incorrect. | Intention comprise et classement correct. | Compréhension maintenue et exactitude améliorée. |
| Question météo | Refus suivi de développements inutiles et non vérifiés. | Refus bref, sans prévision inventée. | Meilleur respect du périmètre et réponse plus concise. |

### Comparaison des métriques RAGAS

| Métrique | Moyenne V01 | Moyenne V03 | Évolution |
|---|---:|---:|---|
| Faithfulness | 0,26 | 0,85 | Forte hausse, mais seulement 6 scores disponibles en V03 contre 8 en V01. |
| Context precision | 0,07 | 0,19 | Hausse limitée ; de nombreux passages FAISS restent peu utiles. |
| Response relevancy | 0,65 | 0,60 | Légère baisse globale, avec 7 scores disponibles en V01 contre 8 en V03. |
| Factual correctness | 0,35 | 0,35 | Moyenne presque inchangée malgré des progrès numériques visibles. |

Ces moyennes ne suffisent pas à résumer l’évolution du système.

La pertinence augmente sur les cas disposant de scores dans les
deux versions, sauf pour la question des joueurs les plus mentionnés :
la V03 s’abstient, alors que la V01 produisait une réponse thématiquement
pertinente mais incorrecte. La baisse globale ne signifie donc pas
une dégradation générale des réponses.

L’exactitude factuelle illustre également les limites du juge :
le classement incorrect des joueurs mentionnés obtenait 0,80 en V01,
tandis que certaines réponses statistiques correctes obtiennent
0,00 en V03. Les causes précises nécessiteraient les jugements
détaillés de RAGAS.

Enfin, la hausse de fidélité accompagne une modification des preuves
transmises à l’évaluateur : la V03 inclut les résultats SQL dans
retrieved_contexts. Elle reflète donc à la fois des réponses mieux
fondées et la disponibilité de ces preuves pour le juge.

### Améliorations confirmées

**Le principal progrès concerne les questions statistiques.**
Les cinq cas numériques ou comparatifs de la V01 produisaient
des résultats incorrects. En V03, les noms et les valeurs essentiels
sont corrects dans les cinq cas, même si quatre réponses omettent
une précision présente dans la référence.

Les requêtes SQL observées utilisent les colonnes adaptées,
appliquent les filtres et produisent les classements nécessaires.
Logfire confirme leur exécution réelle. Les réponses reposent
ainsi sur des résultats structurés plutôt que sur des extrapolations
à partir de quelques passages Excel.

**Les réponses sont également plus maîtrisées.**
Les longues digressions et les inventions relevées en V01 diminuent.
Le refus hors périmètre est plus concis et l’abstention remplace
un classement non justifié pour les mentions de joueurs.

### Limites qui persistent

- La recherche FAISS récupère encore des passages hors sujet,
  incomplets ou redondants.
- Les questions sur les commentaires restent insuffisamment couvertes.
- Certaines réponses omettent les tentatives ou les écarts utiles.
- Des remarques inutiles sur les liens subsistent.
- Les métriques automatiques divergent parfois de la vérification humaine.

### Conclusion

**La V03 améliore nettement l’exactitude des réponses statistiques
sur ce jeu de test.** L’intégration du tool SQL répond à une limite
majeure identifiée en V01 : la recherche de quelques extraits
ne suffisait pas pour filtrer, classer ou comparer les données.

L’amélioration des questions textuelles est plus limitée :
les réponses sont davantage maîtrisées, mais les preuves récupérées
restent insuffisantes pour couvrir l’ensemble des commentaires.

Ces résultats soutiennent l’intérêt de l’architecture hybride.
Ils ne permettent toutefois pas d’attribuer tous les progrès au
seul SQL, puisque le prompt a également évolué, ni de généraliser
la fiabilité du système au-delà des huit cas évalués.

### Priorités d’amélioration à tester

- Adapter la recherche à la source nécessaire : statistiques SQL
  ou commentaires Reddit.
- Nettoyer et diversifier les extraits documentaires.
- Ajouter les précisions utiles : tentatives, joueur en tête et écart.
- Supprimer les remarques non demandées sur les liens.
- Prévoir un comptage pour les questions de fréquence.
- Étendre le jeu de test et conserver une évaluation humaine
  identique pour les prochaines versions.